"""add_rpa_run_date_range

Revision ID: 58a60869c7e1
Revises: a548454f01a1
Create Date: 2025-12-20 04:32:57.159007

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "58a60869c7e1"
down_revision = "a548454f01a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rpa_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("data_start_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("data_end_date", sa.Date(), nullable=True))

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rpa_runs", schema=None) as batch_op:
        batch_op.drop_column("data_end_date")
        batch_op.drop_column("data_start_date")

    # ### end Alembic commands ###
    # ### end Alembic commands ###
