"""merge heads for zod upgrade

Revision ID: 6ea7f2902c6a
Revises: 1234567890ab, a1b2c3d4e5f7
Create Date: 2026-01-17 20:18:10.010353

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "6ea7f2902c6a"
down_revision = ("1234567890ab", "a1b2c3d4e5f7")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
