"""fix timestamp timezone

Revision ID: 981e944594b8
Revises: b77dcffc2d98
Create Date: 2026-01-18 02:03:50.414252

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "981e944594b8"
down_revision = "b77dcffc2d98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lot_master", schema=None) as batch_op:
        batch_op.alter_column(
            "lot_number",
            existing_type=sa.VARCHAR(length=100),
            comment="ロット番号（仕入先発番）",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "first_receipt_date",
            existing_type=sa.DATE(),
            comment="初回入荷日（自動更新）",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "latest_expiry_date",
            existing_type=sa.DATE(),
            comment="傘下receiptの最長有効期限（表示用）",
            existing_nullable=True,
        )

    with op.batch_alter_table("lot_receipts", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("idx_lots_active_pw"), postgresql_where="((status)::text = 'active'::text)"
        )
        batch_op.drop_index(
            batch_op.f("idx_lots_expiry_date"), postgresql_where="(expiry_date IS NOT NULL)"
        )
        batch_op.drop_index(batch_op.f("idx_lots_origin_type"))
        batch_op.drop_index(batch_op.f("idx_lots_product_warehouse"))
        batch_op.drop_index(batch_op.f("idx_lots_pw"))
        batch_op.drop_index(batch_op.f("idx_lots_status"))
        batch_op.drop_index(batch_op.f("idx_lots_supplier"))
        batch_op.drop_index(
            batch_op.f("idx_lots_temporary_lot_key"),
            postgresql_where="(temporary_lot_key IS NOT NULL)",
        )
        batch_op.drop_index(batch_op.f("idx_lots_warehouse"))
        batch_op.drop_index(
            batch_op.f("uq_lot_receipts_expected_lot"),
            postgresql_where="(expected_lot_id IS NOT NULL)",
        )
        batch_op.create_index(
            "idx_lot_receipts_expiry_date",
            ["expiry_date"],
            unique=False,
            postgresql_where=sa.text("expiry_date IS NOT NULL"),
        )
        batch_op.create_index("idx_lot_receipts_origin_type", ["origin_type"], unique=False)
        batch_op.create_index(
            "idx_lot_receipts_product_warehouse", ["product_id", "warehouse_id"], unique=False
        )
        batch_op.create_index("idx_lot_receipts_status", ["status"], unique=False)
        batch_op.create_index("idx_lot_receipts_supplier", ["supplier_id"], unique=False)
        batch_op.create_index(
            "idx_lot_receipts_temporary_lot_key",
            ["temporary_lot_key"],
            unique=False,
            postgresql_where=sa.text("temporary_lot_key IS NOT NULL"),
        )
        batch_op.create_index("idx_lot_receipts_warehouse", ["warehouse_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_lot_receipts_temporary_lot_key", ["temporary_lot_key"]
        )

    with op.batch_alter_table("order_lines", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.drop_index(
            batch_op.f("idx_order_lines_external_product_code"),
            postgresql_where="(external_product_code IS NOT NULL)",
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "locked_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "lock_expires_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True,
        )
        batch_op.drop_index(
            batch_op.f("idx_orders_ocr_source"),
            postgresql_where="(ocr_source_filename IS NOT NULL)",
        )

    with op.batch_alter_table("product_suppliers", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
        )

    with op.batch_alter_table("product_warehouse", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("idx_product_warehouse_active"), postgresql_where="(is_active = true)"
        )

    with op.batch_alter_table("rpa_run_items", schema=None) as batch_op:
        batch_op.alter_column(
            "external_product_code",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=100),
            existing_nullable=True,
        )

    with op.batch_alter_table("warehouse_delivery_routes", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("uq_wdr_warehouse_delivery_default"), postgresql_where="(product_id IS NULL)"
        )
        batch_op.drop_index(
            batch_op.f("uq_wdr_warehouse_delivery_product"),
            postgresql_where="(product_id IS NOT NULL)",
        )

    with op.batch_alter_table("withdrawals", schema=None) as batch_op:
        batch_op.alter_column(
            "lot_id",
            existing_type=sa.BIGINT(),
            comment="レガシー: withdrawal_lines 移行後は未使用",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "quantity",
            existing_type=sa.NUMERIC(precision=15, scale=3),
            comment="レガシー: withdrawal_lines 移行後は未使用",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "cancelled_at",
            existing_type=postgresql.TIMESTAMP(),
            comment=None,
            existing_comment="取消日時",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "cancelled_by",
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment="取消実行者ユーザーID",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "cancel_reason",
            existing_type=sa.VARCHAR(length=50),
            comment=None,
            existing_comment="取消理由",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "cancel_note",
            existing_type=sa.TEXT(),
            comment=None,
            existing_comment="取消メモ",
            existing_nullable=True,
        )
        batch_op.drop_index(
            batch_op.f("idx_withdrawals_cancelled_at"),
            postgresql_where="(cancelled_at IS NOT NULL)",
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("withdrawals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_withdrawals_cancelled_at"),
            ["cancelled_at"],
            unique=False,
            postgresql_where="(cancelled_at IS NOT NULL)",
        )
        batch_op.alter_column(
            "cancel_note", existing_type=sa.TEXT(), comment="取消メモ", existing_nullable=True
        )
        batch_op.alter_column(
            "cancel_reason",
            existing_type=sa.VARCHAR(length=50),
            comment="取消理由",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "cancelled_by",
            existing_type=sa.BIGINT(),
            comment="取消実行者ユーザーID",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "cancelled_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="取消日時",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "quantity",
            existing_type=sa.NUMERIC(precision=15, scale=3),
            comment=None,
            existing_comment="レガシー: withdrawal_lines 移行後は未使用",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "lot_id",
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment="レガシー: withdrawal_lines 移行後は未使用",
            existing_nullable=True,
        )

    with op.batch_alter_table("warehouse_delivery_routes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("uq_wdr_warehouse_delivery_product"),
            ["warehouse_id", "delivery_place_id", "product_id"],
            unique=True,
            postgresql_where="(product_id IS NOT NULL)",
        )
        batch_op.create_index(
            batch_op.f("uq_wdr_warehouse_delivery_default"),
            ["warehouse_id", "delivery_place_id"],
            unique=True,
            postgresql_where="(product_id IS NULL)",
        )

    with op.batch_alter_table("rpa_run_items", schema=None) as batch_op:
        batch_op.alter_column(
            "external_product_code",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )

    with op.batch_alter_table("product_warehouse", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_product_warehouse_active"),
            ["is_active"],
            unique=False,
            postgresql_where="(is_active = true)",
        )

    with op.batch_alter_table("product_suppliers", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_orders_ocr_source"),
            ["ocr_source_filename"],
            unique=False,
            postgresql_where="(ocr_source_filename IS NOT NULL)",
        )
        batch_op.alter_column(
            "lock_expires_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "locked_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("order_lines", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_order_lines_external_product_code"),
            ["external_product_code"],
            unique=False,
            postgresql_where="(external_product_code IS NOT NULL)",
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text("CURRENT_TIMESTAMP"),  # type: ignore[arg-type]
        )

    with op.batch_alter_table("lot_receipts", schema=None) as batch_op:
        batch_op.drop_constraint("uq_lot_receipts_temporary_lot_key", type_="unique")
        batch_op.drop_index("idx_lot_receipts_warehouse")
        batch_op.drop_index(
            "idx_lot_receipts_temporary_lot_key",
            postgresql_where=sa.text("temporary_lot_key IS NOT NULL"),
        )
        batch_op.drop_index("idx_lot_receipts_supplier")
        batch_op.drop_index("idx_lot_receipts_status")
        batch_op.drop_index("idx_lot_receipts_product_warehouse")
        batch_op.drop_index("idx_lot_receipts_origin_type")
        batch_op.drop_index(
            "idx_lot_receipts_expiry_date", postgresql_where=sa.text("expiry_date IS NOT NULL")
        )
        batch_op.create_index(
            batch_op.f("uq_lot_receipts_expected_lot"),
            ["expected_lot_id"],
            unique=True,
            postgresql_where="(expected_lot_id IS NOT NULL)",
        )
        batch_op.create_index(batch_op.f("idx_lots_warehouse"), ["warehouse_id"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_lots_temporary_lot_key"),
            ["temporary_lot_key"],
            unique=False,
            postgresql_where="(temporary_lot_key IS NOT NULL)",
        )
        batch_op.create_index(batch_op.f("idx_lots_supplier"), ["supplier_id"], unique=False)
        batch_op.create_index(batch_op.f("idx_lots_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_lots_pw"), ["product_id", "warehouse_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_lots_product_warehouse"), ["product_id", "warehouse_id"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_lots_origin_type"), ["origin_type"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_lots_expiry_date"),
            ["expiry_date"],
            unique=False,
            postgresql_where="(expiry_date IS NOT NULL)",
        )
        batch_op.create_index(
            batch_op.f("idx_lots_active_pw"),
            ["product_id", "warehouse_id"],
            unique=False,
            postgresql_where="((status)::text = 'active'::text)",
        )

    with op.batch_alter_table("lot_master", schema=None) as batch_op:
        batch_op.alter_column(
            "latest_expiry_date",
            existing_type=sa.DATE(),
            comment=None,
            existing_comment="傘下receiptの最長有効期限（表示用）",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "first_receipt_date",
            existing_type=sa.DATE(),
            comment=None,
            existing_comment="初回入荷日（自動更新）",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "lot_number",
            existing_type=sa.VARCHAR(length=100),
            comment=None,
            existing_comment="ロット番号（仕入先発番）",
            existing_nullable=False,
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###
