"""merge_stock_history_backfill

Revision ID: 26bb6924c845
Revises: d8f000e7240b, z4a5b6c7d8e9
Create Date: 2026-01-16 08:28:12.537164

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "26bb6924c845"
down_revision = ("d8f000e7240b", "z4a5b6c7d8e9")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
