"""add confirmed_by to lot_reservations

Revision ID: 348d4e9f7602
Revises: f0b8334e2d44
Create Date: 2025-12-20 03:40:58.600404

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "348d4e9f7602"
down_revision = "f0b8334e2d44"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("business_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_business_rules_code"))

    with op.batch_alter_table("forecast_current", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_current_key"))
        batch_op.drop_index(batch_op.f("idx_forecast_current_unique"))
        batch_op.create_index(
            "idx_forecast_current_unique",
            ["customer_id", "delivery_place_id", "product_id"],
            unique=False,
        )
        batch_op.create_index(
            "ux_forecast_current_unique",
            ["customer_id", "delivery_place_id", "product_id", "forecast_date", "forecast_period"],
            unique=True,
        )

    with op.batch_alter_table("lot_reservations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "confirmed_by",
                sa.String(length=50),
                nullable=True,
                comment="User who confirmed the reservation",
            )
        )
        batch_op.alter_column(
            "sap_registered_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            type_=sa.DateTime(),
            existing_comment="Timestamp when reservation was registered in SAP",
            existing_nullable=True,
        )
        batch_op.drop_index(
            batch_op.f("idx_lot_reservations_sap_document"),
            postgresql_where="(sap_document_no IS NOT NULL)",
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_users_azure_oid"))

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_users_azure_oid"), ["azure_object_id"], unique=True)

    with op.batch_alter_table("lot_reservations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_lot_reservations_sap_document"),
            ["sap_document_no"],
            unique=False,
            postgresql_where="(sap_document_no IS NOT NULL)",
        )
        batch_op.alter_column(
            "sap_registered_at",
            existing_type=sa.DateTime(),
            type_=postgresql.TIMESTAMP(timezone=True),
            existing_comment="Timestamp when reservation was registered in SAP",
            existing_nullable=True,
        )
        batch_op.drop_column("confirmed_by")

    with op.batch_alter_table("forecast_current", schema=None) as batch_op:
        batch_op.drop_index("ux_forecast_current_unique")
        batch_op.drop_index("idx_forecast_current_unique")
        batch_op.create_index(
            batch_op.f("idx_forecast_current_unique"),
            ["customer_id", "delivery_place_id", "product_id", "forecast_date", "forecast_period"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_forecast_current_key"),
            ["customer_id", "delivery_place_id", "product_id"],
            unique=False,
        )

    with op.batch_alter_table("business_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_business_rules_code"), ["rule_code"], unique=False)

    # ### end Alembic commands ###
    # ### end Alembic commands ###
