"""merge heads

Revision ID: 5de742979df0
Revises: dfd667b4da21
Create Date: 2026-01-18 20:46:24.282398

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "5de742979df0"
down_revision = "dfd667b4da21"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
