"""add system_client_logs table

Revision ID: 9decff574dcb
Revises: 561b887c8e22
Create Date: 2026-01-14 21:47:48.986333

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "9decff574dcb"
down_revision = "561b887c8e22"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table("system_client_logs"):
        op.create_table(
            "system_client_logs",
            sa.Column("id", sa.BigInteger(), nullable=False),
            sa.Column("user_id", sa.BigInteger(), nullable=True),
            sa.Column(
                "level", sa.String(length=20), server_default=sa.text("'info'"), nullable=False
            ),
            sa.Column("message", sa.Text(), nullable=False),
            sa.Column("user_agent", sa.String(length=255), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("system_client_logs", schema=None) as batch_op:
            batch_op.create_index("idx_system_client_logs_created_at", ["created_at"], unique=False)
            batch_op.create_index("idx_system_client_logs_user_id", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_client_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_system_client_logs_user_id")
        batch_op.drop_index("idx_system_client_logs_created_at")

    op.drop_table("system_client_logs")
    # ### end Alembic commands ###
