"""add_cloud_flow_tables

Revision ID: a548454f01a1
Revises: 348d4e9f7602
Create Date: 2025-12-20 04:19:36.635024

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "a548454f01a1"
down_revision = "348d4e9f7602"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloud_flow_configs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("config_key", sa.String(length=100), nullable=False),
        sa.Column("config_value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_key"),
    )
    op.create_table(
        "cloud_flow_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("requested_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("result_message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cloud_flow_jobs", schema=None) as batch_op:
        batch_op.create_index("idx_cloud_flow_jobs_requested_at", ["requested_at"], unique=False)
        batch_op.create_index("idx_cloud_flow_jobs_status", ["status"], unique=False)
        batch_op.create_index("idx_cloud_flow_jobs_type", ["job_type"], unique=False)

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cloud_flow_jobs", schema=None) as batch_op:
        batch_op.drop_index("idx_cloud_flow_jobs_type")
        batch_op.drop_index("idx_cloud_flow_jobs_status")
        batch_op.drop_index("idx_cloud_flow_jobs_requested_at")

    op.drop_table("cloud_flow_jobs")
    op.drop_table("cloud_flow_configs")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
