"""merge_heads

Revision ID: d6977674c857
Revises: fb04bac1471c, y3z4a5b6c7d8
Create Date: 2026-01-13 19:49:39.404959

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "d6977674c857"
down_revision = ("fb04bac1471c", "y3z4a5b6c7d8")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
