"""add_lot_details_shipping_cost_sales_tax

Revision ID: e69e24e713cc
Revises: 3762f908f9df
Create Date: 2026-01-16 22:31:59.476428

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "e69e24e713cc"
down_revision = "3762f908f9df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lot_receipts", sa.Column("shipping_date", sa.Date(), nullable=True, comment="出荷予定日")
    )
    op.add_column(
        "lot_receipts",
        sa.Column(
            "cost_price", sa.Numeric(precision=10, scale=2), nullable=True, comment="仕入単価"
        ),
    )
    op.add_column(
        "lot_receipts",
        sa.Column(
            "sales_price", sa.Numeric(precision=10, scale=2), nullable=True, comment="販売単価"
        ),
    )
    op.add_column(
        "lot_receipts",
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=True, comment="適用税率"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lot_receipts", "tax_rate")
    op.drop_column("lot_receipts", "sales_price")
    op.drop_column("lot_receipts", "cost_price")
    op.drop_column("lot_receipts", "shipping_date")
    # ### end Alembic commands ###
