"""merge heads for clean branch

Revision ID: 561b887c8e22
Revises: d6977674c857, sr1a2b3c4d5e6
Create Date: 2026-01-14 14:54:45.378078

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "561b887c8e22"
down_revision = ("d6977674c857", "sr1a2b3c4d5e6")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
