"""add qty_scale to products

Revision ID: ae0c76e46488
Revises: 981e944594b8
Create Date: 2026-01-18 10:02:07.295556

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "ae0c76e46488"
down_revision = "981e944594b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "qty_scale",
                sa.Integer(),
                server_default="1",
                nullable=False,
                comment="数量スケール（1=通常, 10=小ロット等）",
            )
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("qty_scale")

    # ### end Alembic commands ###
    # ### end Alembic commands ###
