"""merge rpa heads

Revision ID: f0b8334e2d44
Revises: 17625625c5fb, e1f2g3h4i5j6
Create Date: 2025-12-17 20:46:00.952479

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "f0b8334e2d44"
down_revision = ("17625625c5fb", "e1f2g3h4i5j6")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
