import { describe, expect, it } from "vitest";

import { reportUndefinedRoutes, validateRouteDefinitions } from "./validate-routes";

describe("Route permissions validation", () => {
  it("should ensure all MainRoutes paths are defined in routePermissions", () => {
    const actualPaths = [
      "/",
      "/dashboard",
      "/orders",
      "/orders/:orderId",
      "/confirmed-lines",
      "/allocations",
      "/allocations/suggestions",
      "/forecasts",
      "/forecasts/new",
      "/forecasts/:id",
      "/forecasts/:forecastId/edit",
      "/forecasts/import",
      "/forecast",
      "/forecast/list",
      "/inbound-plans",
      "/inbound-plans/new",
      "/inbound-plans/:id",
      "/inbound-plans/:planId/edit",
      "/inventory",
      "/inventory/summary",
      "/inventory/lots",
      "/inventory/moves",
      "/inventory/adjustments",
      "/inventory/adjustments/new",
      "/inventory/adhoc/new",
      "/inventory/excel-view/:productId",
      "/inventory/excel-view/:productId/:customerItemId",
      "/inventory/excel-portal",
      "/inventory/history",
      "/inventory/withdrawals",
      "/inventory/withdrawals/new",
      "/inventory/items/:productId/:warehouseId",
      "/inventory/items/:productId/:warehouseId/:tab",
      "/inventory/lots/:lotId",
      "/masters",
      "/supplier-products",
      "/masters/uom-conversions",
      "/warehouses",
      "/suppliers",
      "/customers",
      "/customer-items",
      "/masters/bulk-load",
      "/masters/supplier-assignments",
      "/masters/shipping-masters",
      "/delivery-places",
      "/warehouse-delivery-routes",
      "/forecast",
      "/forecast/list",
      "/settings/users",
      "/settings/roles",
      "/admin",
      "/admin/operation-logs",
      "/admin/business-rules",
      "/admin/batch-jobs",
      "/admin/master-change-logs",
      "/admin/seed-snapshots",
      "/admin/system-settings",
      "/admin/logs",
      "/admin/client-logs",
      "/admin/export",
      "/debug/db",
      "/debug/db/:tab",
      "/calendar",
      "/rpa",
      "/rpa/material-delivery-simple",
      "/rpa/generic-cloud-flow",
      "/rpa/smartread",
      "/rpa/smartread/:tab",
      "/rpa/material-delivery-note",
      "/rpa/material-delivery-note/step1",
      "/rpa/material-delivery-note/csv-import",
      "/rpa/material-delivery-note/step2",
      "/rpa/material-delivery-note/step3/plan",
      "/rpa/material-delivery-note/step3",
      "/rpa/material-delivery-note/runs",
      "/rpa/material-delivery-note/layer-codes",
      "/rpa/material-delivery-note/runs/:runId",
      "/rpa/material-delivery-note/runs/:runId/monitor",
      "/rpa/material-delivery-note/step3/:runId",
      "/rpa/material-delivery-note/step4",
      "/rpa/material-delivery-note/step4/:runId",
      "/ocr-results",
      "/help/flow-map",
      "/help/database-schema",
      "/help/database-schema/:tab",
      "/sap",
      "/sap/:tab",
    ];

    const result = validateRouteDefinitions(actualPaths);
    if (result.undefinedPaths.length > 0) {
      reportUndefinedRoutes(result.undefinedPaths);
    }

    expect(result.undefinedPaths).toEqual([]);
  });
});
