import { format } from "date-fns";
import { useState, useMemo, useEffect } from "react";
import { toast } from "sonner";

import { useCreateForecast } from "../hooks";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  Button,
  Label,
  Input,
} from "@/components/ui";
import { SearchableSelect } from "@/components/ui/form/SearchableSelect";
import { useDeliveryPlaces } from "@/features/delivery-places/hooks";
import { useCustomersQuery, useProductsQuery } from "@/hooks/api/useMastersQuery";

interface AddForecastDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess?: () => void;
}

// eslint-disable-next-line max-lines-per-function -- 関連する画面ロジックを1箇所で管理するため
export function AddForecastDialog({ open, onOpenChange, onSuccess }: AddForecastDialogProps) {
  const [customerId, setCustomerId] = useState<string>("");
  const [deliveryPlaceId, setDeliveryPlaceId] = useState<string>("");
  const [productGroupId, setProductGroupId] = useState<string>("");
  const [forecastDate, setForecastDate] = useState<string>(format(new Date(), "yyyy-MM-dd"));
  const [quantity, setQuantity] = useState<string>("");
  const [unit, setUnit] = useState<string>("EA");

  const { data: customers = [] } = useCustomersQuery({ enabled: open });
  const { data: products = [] } = useProductsQuery({ enabled: open });
  const { data: deliveryPlaces = [] } = useDeliveryPlaces(
    { ...(customerId ? { customerId: Number(customerId) } : {}) },
    { enabled: open && !!customerId },
  );

  const createMutation = useCreateForecast();

  // Reset fields when customer changes
  useEffect(() => {
    setDeliveryPlaceId("");
  }, [customerId]);

  const customerOptions = useMemo(
    () =>
      customers.map((c) => ({
        value: String(c.id),
        label: `${c.customer_code} - ${c.customer_name}`,
      })),
    [customers],
  );

  const productOptions = useMemo(
    () =>
      products.map((p) => ({
        value: String(p.id),
        label: `${p.maker_part_no} - ${p.display_name}`,
      })),
    [products],
  );

  const deliveryPlaceOptions = useMemo(
    () =>
      deliveryPlaces.map((dp) => ({
        value: String(dp.id),
        label: `${dp.delivery_place_code} - ${dp.delivery_place_name}`,
      })),
    [deliveryPlaces],
  );

  const handleSubmit = async () => {
    if (!customerId || !deliveryPlaceId || !productGroupId || !forecastDate || !quantity) {
      toast.error("必須項目を入力してください");
      return;
    }

    try {
      await createMutation.mutateAsync({
        customer_id: Number(customerId),
        delivery_place_id: Number(deliveryPlaceId),
        supplier_item_id: Number(productGroupId),
        forecast_date: forecastDate,
        forecast_quantity: Number(quantity),
        unit,
        // forecast_period is now optional and generated by backend if omitted
      } as Parameters<typeof createMutation.mutateAsync>[0]);
      toast.success("フォーキャストを追加しました");
      onOpenChange(false);
      onSuccess?.();
      // Reset form
      setCustomerId("");
      setDeliveryPlaceId("");
      setProductGroupId("");
      setQuantity("");
    } catch (error) {
      const err = error as { response?: { data?: { detail?: string } }; message?: string };
      console.error("Create failed:", error);
      const errorMessage = err.response?.data?.detail || err.message || "追加に失敗しました";
      toast.error(`追加に失敗しました: ${errorMessage}`);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>フォーキャストの手動追加</DialogTitle>
        </DialogHeader>

        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="customer">得意先 *</Label>
            <SearchableSelect
              options={customerOptions}
              value={customerId}
              onChange={setCustomerId}
              placeholder="得意先を選択..."
            />
          </div>

          <div className="grid gap-2">
            <Label htmlFor="delivery-place">納入場所 *</Label>
            <SearchableSelect
              options={deliveryPlaceOptions}
              value={deliveryPlaceId}
              onChange={setDeliveryPlaceId}
              placeholder="納入場所を選択..."
              disabled={!customerId}
            />
          </div>

          <div className="grid gap-2">
            <Label htmlFor="product">製品 *</Label>
            <SearchableSelect
              options={productOptions}
              value={productGroupId}
              onChange={setProductGroupId}
              placeholder="製品を選択..."
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label htmlFor="forecast-date">予測日 *</Label>
              <Input
                id="forecast-date"
                type="date"
                value={forecastDate}
                onChange={(e) => setForecastDate(e.target.value)}
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="quantity">数量 *</Label>
              <Input
                id="quantity"
                type="number"
                min="0"
                step="any"
                value={quantity}
                onChange={(e) => setQuantity(e.target.value)}
                placeholder="0.00"
              />
            </div>
          </div>

          <div className="grid gap-2">
            <Label htmlFor="unit">単位</Label>
            <Input id="unit" value={unit} onChange={(e) => setUnit(e.target.value)} />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            キャンセル
          </Button>
          <Button onClick={handleSubmit} disabled={createMutation.isPending}>
            {createMutation.isPending ? "追加中..." : "追加"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
