"""initial_schema

Revision ID: 000000000000
Revises:
Create Date: 2025-12-08 17:16:55.753558

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "000000000000"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("result_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "job_type IN ('allocation_suggestion', 'allocation_finalize', 'inventory_sync', 'data_import', 'report_generation')",
            name="chk_batch_jobs_type",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')", name="chk_batch_jobs_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("batch_jobs", schema=None) as batch_op:
        batch_op.create_index("idx_batch_jobs_created", ["created_at"], unique=False)
        batch_op.create_index("idx_batch_jobs_status", ["status"], unique=False)
        batch_op.create_index("idx_batch_jobs_type", ["job_type"], unique=False)

    op.create_table(
        "business_rules",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("rule_code", sa.String(length=50), nullable=False),
        sa.Column("rule_name", sa.String(length=100), nullable=False),
        sa.Column("rule_type", sa.String(length=50), nullable=False),
        sa.Column(
            "rule_parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "rule_type IN ('allocation', 'expiry_warning', 'kanban', 'inventory_sync_alert', 'other')",
            name="chk_business_rules_type",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_code"),
    )
    with op.batch_alter_table("business_rules", schema=None) as batch_op:
        batch_op.create_index(
            "idx_business_rules_active",
            ["is_active"],
            unique=False,
            postgresql_where=sa.text("is_active = TRUE"),
        )
        batch_op.create_index("idx_business_rules_code", ["rule_code"], unique=False)
        batch_op.create_index("idx_business_rules_type", ["rule_type"], unique=False)

    op.create_table(
        "customers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("contact_name", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_code", name="uq_customers_customer_code"),
    )
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.create_index("idx_customers_code", ["customer_code"], unique=False)

    op.create_table(
        "forecast_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("forecast_date", sa.Date(), nullable=False),
        sa.Column("forecast_quantity", sa.Numeric(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("forecast_period", sa.String(length=7), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forecast_history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_forecast_history_key",
            ["customer_id", "delivery_place_id", "product_id"],
            unique=False,
        )

    op.create_table(
        "products",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("maker_part_code", sa.String(length=100), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("base_unit", sa.String(length=20), nullable=False),
        sa.Column("consumption_limit_days", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("internal_unit", sa.String(length=20), server_default="CAN", nullable=False),
        sa.Column("external_unit", sa.String(length=20), server_default="KG", nullable=False),
        sa.Column(
            "qty_per_internal_unit",
            sa.Numeric(precision=10, scale=4),
            server_default="1.0",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("maker_part_code", name="uq_products_maker_part_code"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index("idx_products_code", ["maker_part_code"], unique=False)
        batch_op.create_index("idx_products_name", ["product_name"], unique=False)

    op.create_table(
        "roles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("role_code", sa.String(length=50), nullable=False),
        sa.Column("role_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_code", name="uq_roles_role_code"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index("idx_roles_code", ["role_code"], unique=False)

    op.create_table(
        "seed_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False, comment="スナップショット名"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="作成日時"),
        sa.Column(
            "params_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            comment="展開後の最終パラメータ（profile解決後）",
        ),
        sa.Column(
            "profile_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
            comment="使用したプロファイル設定",
        ),
        sa.Column(
            "csv_dir", sa.Text(), nullable=True, comment="CSVエクスポートディレクトリ（オプション）"
        ),
        sa.Column(
            "summary_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
            comment="生成結果のサマリ（件数、検証結果など）",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_code", sa.String(length=50), nullable=False),
        sa.Column("supplier_name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supplier_code", name="uq_suppliers_supplier_code"),
    )
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.create_index("idx_suppliers_code", ["supplier_code"], unique=False)

    op.create_table(
        "system_configs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("config_key", sa.String(length=100), nullable=False),
        sa.Column("config_value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_key", name="uq_system_configs_key"),
    )
    with op.batch_alter_table("system_configs", schema=None) as batch_op:
        batch_op.create_index("idx_system_configs_key", ["config_key"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "auth_provider", sa.String(length=50), server_default=sa.text("'local'"), nullable=False
        ),
        sa.Column("azure_object_id", sa.String(length=100), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("azure_object_id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("username", name="uq_users_username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            "idx_users_active",
            ["is_active"],
            unique=False,
            postgresql_where=sa.text("is_active = TRUE"),
        )
        batch_op.create_index("idx_users_auth_provider", ["auth_provider"], unique=False)
        batch_op.create_index("idx_users_azure_oid", ["azure_object_id"], unique=True)
        batch_op.create_index("idx_users_email", ["email"], unique=False)
        batch_op.create_index("idx_users_username", ["username"], unique=False)

    op.create_table(
        "warehouses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_code", sa.String(length=50), nullable=False),
        sa.Column("warehouse_name", sa.String(length=200), nullable=False),
        sa.Column("warehouse_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "warehouse_type IN ('internal', 'external', 'supplier')", name="chk_warehouse_type"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_code", name="uq_warehouses_warehouse_code"),
    )
    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.create_index("idx_warehouses_code", ["warehouse_code"], unique=False)
        batch_op.create_index("idx_warehouses_type", ["warehouse_type"], unique=False)

    op.create_table(
        "customer_items",
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("external_product_code", sa.String(length=100), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=True),
        sa.Column("base_unit", sa.String(length=20), nullable=False),
        sa.Column("pack_unit", sa.String(length=20), nullable=True),
        sa.Column("pack_quantity", sa.Integer(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("shipping_document_template", sa.Text(), nullable=True),
        sa.Column("sap_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("customer_id", "external_product_code"),
    )
    with op.batch_alter_table("customer_items", schema=None) as batch_op:
        batch_op.create_index("idx_customer_items_product", ["product_id"], unique=False)
        batch_op.create_index("idx_customer_items_supplier", ["supplier_id"], unique=False)

    op.create_table(
        "delivery_places",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("jiku_code", sa.String(length=50), nullable=True),
        sa.Column("delivery_place_code", sa.String(length=50), nullable=False),
        sa.Column("delivery_place_name", sa.String(length=200), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_place_code", name="uq_delivery_places_code"),
    )
    with op.batch_alter_table("delivery_places", schema=None) as batch_op:
        batch_op.create_index("idx_delivery_places_code", ["delivery_place_code"], unique=False)
        batch_op.create_index("idx_delivery_places_customer", ["customer_id"], unique=False)

    op.create_table(
        "inbound_plans",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("plan_number", sa.String(length=50), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("planned_arrival_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'planned'"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('planned','partially_received','received','cancelled')",
            name="chk_inbound_plans_status",
        ),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_number", name="inbound_plans_plan_number_key"),
    )
    with op.batch_alter_table("inbound_plans", schema=None) as batch_op:
        batch_op.create_index("idx_inbound_plans_date", ["planned_arrival_date"], unique=False)
        batch_op.create_index("idx_inbound_plans_status", ["status"], unique=False)
        batch_op.create_index("idx_inbound_plans_supplier", ["supplier_id"], unique=False)

    op.create_table(
        "master_change_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("table_name", sa.String(length=50), nullable=False),
        sa.Column("record_id", sa.BigInteger(), nullable=False),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column(
            "old_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "new_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("changed_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "changed_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "change_type IN ('insert', 'update', 'delete')", name="chk_master_change_logs_type"
        ),
        sa.ForeignKeyConstraint(["changed_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("master_change_logs", schema=None) as batch_op:
        batch_op.create_index("idx_master_change_logs_changed", ["changed_at"], unique=False)
        batch_op.create_index("idx_master_change_logs_record", ["record_id"], unique=False)
        batch_op.create_index("idx_master_change_logs_table", ["table_name"], unique=False)
        batch_op.create_index("idx_master_change_logs_user", ["changed_by"], unique=False)

    op.create_table(
        "operation_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.String(length=50), nullable=False),
        sa.Column("target_table", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "operation_type IN ('create', 'update', 'delete', 'login', 'logout', 'export')",
            name="chk_operation_logs_type",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("operation_logs", schema=None) as batch_op:
        batch_op.create_index("idx_operation_logs_created", ["created_at"], unique=False)
        batch_op.create_index("idx_operation_logs_table", ["target_table"], unique=False)
        batch_op.create_index("idx_operation_logs_type", ["operation_type"], unique=False)
        batch_op.create_index("idx_operation_logs_user", ["user_id"], unique=False)

    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("locked_by_user_id", sa.Integer(), nullable=True),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("lock_expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["locked_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_number", name="uq_orders_order_number"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index("idx_orders_customer", ["customer_id"], unique=False)
        batch_op.create_index("idx_orders_date", ["order_date"], unique=False)
        batch_op.create_index(
            "idx_orders_lock_expires",
            ["lock_expires_at"],
            unique=False,
            postgresql_where=sa.text("lock_expires_at IS NOT NULL"),
        )
        batch_op.create_index("idx_orders_locked_by", ["locked_by_user_id"], unique=False)

    op.create_table(
        "product_suppliers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "supplier_id", name="uq_product_supplier"),
    )
    with op.batch_alter_table("product_suppliers", schema=None) as batch_op:
        batch_op.create_index(
            "uq_product_primary_supplier",
            ["product_id"],
            unique=True,
            postgresql_where=sa.text("is_primary = true"),
        )

    op.create_table(
        "product_uom_conversions",
        sa.Column("conversion_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("external_unit", sa.String(length=20), nullable=False),
        sa.Column("factor", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversion_id"),
        sa.UniqueConstraint("product_id", "external_unit", name="uq_uom_conversions_product_unit"),
    )
    op.create_table(
        "system_client_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("level", sa.String(length=20), server_default=sa.text("'info'"), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("system_client_logs", schema=None) as batch_op:
        batch_op.create_index("idx_system_client_logs_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_system_client_logs_user_id", ["user_id"], unique=False)

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.create_index("idx_user_roles_role", ["role_id"], unique=False)
        batch_op.create_index("idx_user_roles_user", ["user_id"], unique=False)

    op.create_table(
        "user_supplier_assignments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "supplier_id", name="uq_user_supplier_assignments_user_supplier"
        ),
    )
    with op.batch_alter_table("user_supplier_assignments", schema=None) as batch_op:
        batch_op.create_index(
            "idx_user_supplier_assignments_primary",
            ["is_primary"],
            unique=False,
            postgresql_where=sa.text("is_primary = TRUE"),
        )
        batch_op.create_index(
            "idx_user_supplier_assignments_supplier", ["supplier_id"], unique=False
        )
        batch_op.create_index("idx_user_supplier_assignments_user", ["user_id"], unique=False)
        batch_op.create_index(
            "uq_user_supplier_primary_per_supplier",
            ["supplier_id"],
            unique=True,
            postgresql_where=sa.text("is_primary = TRUE"),
        )

    op.create_table(
        "customer_item_jiku_mappings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("external_product_code", sa.String(length=100), nullable=False),
        sa.Column("jiku_code", sa.String(length=50), nullable=False),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="FALSE", nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "external_product_code"],
            ["customer_items.customer_id", "customer_items.external_product_code"],
            name="fk_customer_item_jiku_customer_item",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_id", "external_product_code", "jiku_code", name="uq_customer_item_jiku"
        ),
    )
    op.create_table(
        "forecast_current",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("forecast_date", sa.Date(), nullable=False),
        sa.Column("forecast_quantity", sa.Numeric(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("forecast_period", sa.String(length=7), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forecast_current", schema=None) as batch_op:
        batch_op.create_index(
            "ix_forecast_current_key",
            ["customer_id", "delivery_place_id", "product_id"],
            unique=False,
        )
        batch_op.create_index(
            "ux_forecast_current_unique",
            ["customer_id", "delivery_place_id", "product_id", "forecast_date", "forecast_period"],
            unique=True,
        )

    op.create_table(
        "inbound_plan_lines",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("inbound_plan_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("planned_quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["inbound_plan_id"], ["inbound_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inbound_plan_lines", schema=None) as batch_op:
        batch_op.create_index("idx_inbound_plan_lines_plan", ["inbound_plan_id"], unique=False)
        batch_op.create_index("idx_inbound_plan_lines_product", ["product_id"], unique=False)

    op.create_table(
        "expected_lots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("inbound_plan_line_id", sa.BigInteger(), nullable=False),
        sa.Column("expected_lot_number", sa.String(length=100), nullable=True),
        sa.Column("expected_quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("expected_expiry_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["inbound_plan_line_id"], ["inbound_plan_lines.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expected_lots", schema=None) as batch_op:
        batch_op.create_index("idx_expected_lots_line", ["inbound_plan_line_id"], unique=False)
        batch_op.create_index("idx_expected_lots_number", ["expected_lot_number"], unique=False)

    op.create_table(
        "order_lines",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column("order_quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("converted_quantity", sa.Numeric(precision=15, scale=3), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "sap_order_no",
            sa.String(length=100),
            nullable=True,
            comment="SAP受注番号（登録済みの場合）",
        ),
        sa.Column("shipping_document_text", sa.Text(), nullable=True, comment="出荷表テキスト"),
        sa.Column(
            "order_type",
            sa.String(length=20),
            server_default=sa.text("'ORDER'"),
            nullable=False,
            comment="需要種別: FORECAST_LINKED / KANBAN / SPOT / ORDER",
        ),
        sa.Column(
            "forecast_id",
            sa.BigInteger(),
            nullable=True,
            comment="紐づく予測ID（FORECAST_LINKEDの場合）",
        ),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "order_type IN ('FORECAST_LINKED', 'KANBAN', 'SPOT', 'ORDER')",
            name="chk_order_lines_order_type",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'allocated', 'shipped', 'completed', 'cancelled')",
            name="chk_order_lines_status",
        ),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["forecast_id"], ["forecast_current.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_lines", schema=None) as batch_op:
        batch_op.create_index("idx_order_lines_date", ["delivery_date"], unique=False)
        batch_op.create_index("idx_order_lines_delivery_place", ["delivery_place_id"], unique=False)
        batch_op.create_index("idx_order_lines_forecast_id", ["forecast_id"], unique=False)
        batch_op.create_index("idx_order_lines_order", ["order_id"], unique=False)
        batch_op.create_index("idx_order_lines_order_type", ["order_type"], unique=False)
        batch_op.create_index("idx_order_lines_product", ["product_id"], unique=False)
        batch_op.create_index(
            "idx_order_lines_sap_order_no",
            ["sap_order_no"],
            unique=False,
            postgresql_where=sa.text("sap_order_no IS NOT NULL"),
        )
        batch_op.create_index("idx_order_lines_status", ["status"], unique=False)

    op.create_table(
        "lots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("lot_number", sa.String(length=100), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=True),
        sa.Column("expected_lot_id", sa.BigInteger(), nullable=True),
        sa.Column("received_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "current_quantity",
            sa.Numeric(precision=15, scale=3),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "allocated_quantity",
            sa.Numeric(precision=15, scale=3),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("lock_reason", sa.Text(), nullable=True),
        sa.Column(
            "locked_quantity",
            sa.Numeric(precision=15, scale=3),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "inspection_status",
            sa.String(length=20),
            server_default=sa.text("'not_required'"),
            nullable=False,
        ),
        sa.Column("inspection_date", sa.Date(), nullable=True),
        sa.Column("inspection_cert_number", sa.String(length=100), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "origin_type", sa.String(length=20), server_default=sa.text("'order'"), nullable=False
        ),
        sa.Column("origin_reference", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "inspection_status IN ('not_required','pending','passed','failed')",
            name="chk_lots_inspection_status",
        ),
        sa.CheckConstraint(
            "origin_type IN ('order','forecast','sample','safety_stock','adhoc')",
            name="chk_lots_origin_type",
        ),
        sa.CheckConstraint(
            "status IN ('active','depleted','expired','quarantine','locked')",
            name="chk_lots_status",
        ),
        sa.CheckConstraint(
            "allocated_quantity + locked_quantity <= current_quantity",
            name="chk_lots_allocation_limit",
        ),
        sa.CheckConstraint("allocated_quantity >= 0", name="chk_lots_allocated_quantity"),
        sa.CheckConstraint("current_quantity >= 0", name="chk_lots_current_quantity"),
        sa.CheckConstraint("locked_quantity >= 0", name="chk_lots_locked_quantity"),
        sa.ForeignKeyConstraint(["expected_lot_id"], ["expected_lots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "lot_number", "product_id", "warehouse_id", name="uq_lots_number_product_warehouse"
        ),
    )
    with op.batch_alter_table("lots", schema=None) as batch_op:
        batch_op.create_index(
            "idx_lots_expiry_date",
            ["expiry_date"],
            unique=False,
            postgresql_where=sa.text("expiry_date IS NOT NULL"),
        )
        batch_op.create_index("idx_lots_number", ["lot_number"], unique=False)
        batch_op.create_index("idx_lots_origin_type", ["origin_type"], unique=False)
        batch_op.create_index(
            "idx_lots_product_warehouse", ["product_id", "warehouse_id"], unique=False
        )
        batch_op.create_index("idx_lots_status", ["status"], unique=False)
        batch_op.create_index("idx_lots_supplier", ["supplier_id"], unique=False)
        batch_op.create_index("idx_lots_warehouse", ["warehouse_id"], unique=False)

    op.create_table(
        "adjustments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=False),
        sa.Column("adjustment_type", sa.String(length=20), nullable=False),
        sa.Column("adjusted_quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("adjusted_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "adjusted_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "adjustment_type IN ('physical_count','damage','loss','found','other')",
            name="chk_adjustments_type",
        ),
        sa.ForeignKeyConstraint(["adjusted_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("adjustments", schema=None) as batch_op:
        batch_op.create_index("idx_adjustments_date", ["adjusted_at"], unique=False)
        batch_op.create_index("idx_adjustments_lot", ["lot_id"], unique=False)

    op.create_table(
        "allocation_suggestions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_line_id", sa.BigInteger(), nullable=True),
        sa.Column("forecast_period", sa.String(length=7), nullable=False),
        sa.Column("forecast_id", sa.BigInteger(), nullable=True),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("allocation_type", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["forecast_id"], ["forecast_current.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("allocation_suggestions", schema=None) as batch_op:
        batch_op.create_index("idx_allocation_suggestions_customer", ["customer_id"], unique=False)
        batch_op.create_index("idx_allocation_suggestions_forecast", ["forecast_id"], unique=False)
        batch_op.create_index("idx_allocation_suggestions_lot", ["lot_id"], unique=False)
        batch_op.create_index(
            "idx_allocation_suggestions_period", ["forecast_period"], unique=False
        )
        batch_op.create_index("idx_allocation_suggestions_product", ["product_id"], unique=False)

    op.create_table(
        "allocation_traces",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_line_id", sa.BigInteger(), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=True),
        sa.Column("score", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("allocated_qty", sa.Numeric(precision=15, scale=3), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "decision IN ('adopted', 'rejected', 'partial')", name="chk_allocation_traces_decision"
        ),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["order_line_id"], ["order_lines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("allocation_traces", schema=None) as batch_op:
        batch_op.create_index("idx_allocation_traces_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_allocation_traces_lot", ["lot_id"], unique=False)
        batch_op.create_index("idx_allocation_traces_order_line", ["order_line_id"], unique=False)

    op.create_table(
        "allocations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("order_line_id", sa.BigInteger(), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=True),
        sa.Column("inbound_plan_line_id", sa.BigInteger(), nullable=True),
        sa.Column("allocated_quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column(
            "allocation_type",
            sa.String(length=10),
            server_default=sa.text("'soft'"),
            nullable=False,
            comment="Allocation type: soft (provisional) or hard (confirmed)",
        ),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'allocated'"), nullable=False
        ),
        sa.Column(
            "confirmed_at",
            sa.DateTime(),
            nullable=True,
            comment="Hard allocation confirmation timestamp",
        ),
        sa.Column(
            "confirmed_by",
            sa.String(length=100),
            nullable=True,
            comment="User who confirmed the allocation",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint("allocation_type IN ('soft', 'hard')", name="chk_allocation_type"),
        sa.CheckConstraint(
            "status IN ('allocated', 'provisional', 'shipped', 'cancelled')",
            name="chk_allocations_status",
        ),
        sa.ForeignKeyConstraint(
            ["inbound_plan_line_id"], ["inbound_plan_lines.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_line_id"], ["order_lines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.create_index("idx_allocations_allocation_type", ["allocation_type"], unique=False)
        batch_op.create_index(
            "idx_allocations_inbound_plan_line", ["inbound_plan_line_id"], unique=False
        )
        batch_op.create_index("idx_allocations_lot", ["lot_id"], unique=False)
        batch_op.create_index("idx_allocations_order_line", ["order_line_id"], unique=False)
        batch_op.create_index("idx_allocations_status", ["status"], unique=False)

    op.create_table(
        "stock_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=False),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("quantity_change", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("quantity_after", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "transaction_date",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "transaction_type IN ('inbound','allocation','shipment','adjustment','return')",
            name="chk_stock_history_type",
        ),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_history", schema=None) as batch_op:
        batch_op.create_index("idx_stock_history_date", ["transaction_date"], unique=False)
        batch_op.create_index("idx_stock_history_lot", ["lot_id"], unique=False)
        batch_op.create_index("idx_stock_history_type", ["transaction_type"], unique=False)

    # Create views from SQL file
    from pathlib import Path

    migration_dir = Path(__file__).resolve().parent
    backend_dir = migration_dir.parents[1]
    sql_path = backend_dir / "sql" / "views" / "create_views.sql"

    with open(sql_path, encoding="utf-8") as f:
        sql_content = f.read()
        statements = sql_content.split(";")
        for statement in statements:
            if statement.strip():
                op.execute(statement)

    # Seed initial roles and admin user
    op.execute("""
        INSERT INTO roles (role_code, role_name, description, created_at, updated_at) 
        VALUES ('admin', 'Administrator', 'System Administrator', NOW(), NOW()) 
        ON CONFLICT (role_code) DO NOTHING;
    """)
    op.execute("""
        INSERT INTO roles (role_code, role_name, description, created_at, updated_at) 
        VALUES ('user', 'General User', 'General User', NOW(), NOW()) 
        ON CONFLICT (role_code) DO NOTHING;
    """)
    op.execute("""
        INSERT INTO roles (role_code, role_name, description, created_at, updated_at) 
        VALUES ('viewer', 'Read-only Viewer', 'Read-only Viewer', NOW(), NOW()) 
        ON CONFLICT (role_code) DO NOTHING;
    """)

    op.execute("""
        INSERT INTO users (username, email, password_hash, display_name, is_active, auth_provider, created_at, updated_at)
        VALUES ('admin', 'admin@example.com', '$2b$12$TuwV8/qk6Y6vISuyQCh8l.VLq3TT36m06j21WFarf29eMwYhQIYmS', 'System Admin', true, 'local', NOW(), NOW())
        ON CONFLICT (username) DO NOTHING;
    """)

    op.execute("""
        INSERT INTO user_roles (user_id, role_id, assigned_at)
        SELECT u.id, r.id, NOW()
        FROM users u, roles r
        WHERE u.username = 'admin' AND r.role_code = 'admin'
        ON CONFLICT (user_id, role_id) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop views first
    op.execute("DROP VIEW IF EXISTS public.v_customer_item_jiku_mappings CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_user_supplier_assignments CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_warehouse_code_to_id CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_supplier_code_to_id CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_lots_with_master CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_candidate_lots_by_order_line CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_forecast_order_pairs CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_delivery_place_code_to_id CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_customer_code_to_id CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_order_line_context CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_lot_available_qty CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_customer_daily_products CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_lot_current_stock CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_product_code_to_id CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_order_line_details CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_inventory_summary CASCADE")
    op.execute("DROP VIEW IF EXISTS public.v_lot_details CASCADE")

    with op.batch_alter_table("stock_history", schema=None) as batch_op:
        batch_op.drop_index("idx_stock_history_type")
        batch_op.drop_index("idx_stock_history_lot")
        batch_op.drop_index("idx_stock_history_date")

    op.drop_table("stock_history")
    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.drop_index("idx_allocations_status")
        batch_op.drop_index("idx_allocations_order_line")
        batch_op.drop_index("idx_allocations_lot")
        batch_op.drop_index("idx_allocations_inbound_plan_line")
        batch_op.drop_index("idx_allocations_allocation_type")

    op.drop_table("allocations")
    with op.batch_alter_table("allocation_traces", schema=None) as batch_op:
        batch_op.drop_index("idx_allocation_traces_order_line")
        batch_op.drop_index("idx_allocation_traces_lot")
        batch_op.drop_index("idx_allocation_traces_created_at")

    op.drop_table("allocation_traces")
    with op.batch_alter_table("allocation_suggestions", schema=None) as batch_op:
        batch_op.drop_index("idx_allocation_suggestions_product")
        batch_op.drop_index("idx_allocation_suggestions_period")
        batch_op.drop_index("idx_allocation_suggestions_lot")
        batch_op.drop_index("idx_allocation_suggestions_forecast")
        batch_op.drop_index("idx_allocation_suggestions_customer")

    op.drop_table("allocation_suggestions")
    with op.batch_alter_table("adjustments", schema=None) as batch_op:
        batch_op.drop_index("idx_adjustments_lot")
        batch_op.drop_index("idx_adjustments_date")

    op.drop_table("adjustments")
    with op.batch_alter_table("lots", schema=None) as batch_op:
        batch_op.drop_index("idx_lots_warehouse")
        batch_op.drop_index("idx_lots_supplier")
        batch_op.drop_index("idx_lots_status")
        batch_op.drop_index("idx_lots_product_warehouse")
        batch_op.drop_index("idx_lots_origin_type")
        batch_op.drop_index("idx_lots_number")
        batch_op.drop_index(
            "idx_lots_expiry_date", postgresql_where=sa.text("expiry_date IS NOT NULL")
        )

    op.drop_table("lots")
    with op.batch_alter_table("order_lines", schema=None) as batch_op:
        batch_op.drop_index("idx_order_lines_status")
        batch_op.drop_index(
            "idx_order_lines_sap_order_no", postgresql_where=sa.text("sap_order_no IS NOT NULL")
        )
        batch_op.drop_index("idx_order_lines_product")
        batch_op.drop_index("idx_order_lines_order_type")
        batch_op.drop_index("idx_order_lines_order")
        batch_op.drop_index("idx_order_lines_forecast_id")
        batch_op.drop_index("idx_order_lines_delivery_place")
        batch_op.drop_index("idx_order_lines_date")

    op.drop_table("order_lines")
    with op.batch_alter_table("expected_lots", schema=None) as batch_op:
        batch_op.drop_index("idx_expected_lots_number")
        batch_op.drop_index("idx_expected_lots_line")

    op.drop_table("expected_lots")
    with op.batch_alter_table("inbound_plan_lines", schema=None) as batch_op:
        batch_op.drop_index("idx_inbound_plan_lines_product")
        batch_op.drop_index("idx_inbound_plan_lines_plan")

    op.drop_table("inbound_plan_lines")
    with op.batch_alter_table("forecast_current", schema=None) as batch_op:
        batch_op.drop_index("ux_forecast_current_unique")
        batch_op.drop_index("ix_forecast_current_key")

    op.drop_table("forecast_current")
    op.drop_table("customer_item_jiku_mappings")
    with op.batch_alter_table("user_supplier_assignments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_user_supplier_primary_per_supplier", postgresql_where=sa.text("is_primary = TRUE")
        )
        batch_op.drop_index("idx_user_supplier_assignments_user")
        batch_op.drop_index("idx_user_supplier_assignments_supplier")
        batch_op.drop_index(
            "idx_user_supplier_assignments_primary", postgresql_where=sa.text("is_primary = TRUE")
        )

    op.drop_table("user_supplier_assignments")
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.drop_index("idx_user_roles_user")
        batch_op.drop_index("idx_user_roles_role")

    op.drop_table("user_roles")
    with op.batch_alter_table("system_client_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_system_client_logs_user_id")
        batch_op.drop_index("idx_system_client_logs_created_at")

    op.drop_table("system_client_logs")
    op.drop_table("product_uom_conversions")
    with op.batch_alter_table("product_suppliers", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_product_primary_supplier", postgresql_where=sa.text("is_primary = true")
        )

    op.drop_table("product_suppliers")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("idx_orders_locked_by")
        batch_op.drop_index(
            "idx_orders_lock_expires", postgresql_where=sa.text("lock_expires_at IS NOT NULL")
        )
        batch_op.drop_index("idx_orders_date")
        batch_op.drop_index("idx_orders_customer")

    op.drop_table("orders")
    with op.batch_alter_table("operation_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_operation_logs_user")
        batch_op.drop_index("idx_operation_logs_type")
        batch_op.drop_index("idx_operation_logs_table")
        batch_op.drop_index("idx_operation_logs_created")

    op.drop_table("operation_logs")
    with op.batch_alter_table("master_change_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_master_change_logs_user")
        batch_op.drop_index("idx_master_change_logs_table")
        batch_op.drop_index("idx_master_change_logs_record")
        batch_op.drop_index("idx_master_change_logs_changed")

    op.drop_table("master_change_logs")
    with op.batch_alter_table("inbound_plans", schema=None) as batch_op:
        batch_op.drop_index("idx_inbound_plans_supplier")
        batch_op.drop_index("idx_inbound_plans_status")
        batch_op.drop_index("idx_inbound_plans_date")

    op.drop_table("inbound_plans")
    with op.batch_alter_table("delivery_places", schema=None) as batch_op:
        batch_op.drop_index("idx_delivery_places_customer")
        batch_op.drop_index("idx_delivery_places_code")

    op.drop_table("delivery_places")
    with op.batch_alter_table("customer_items", schema=None) as batch_op:
        batch_op.drop_index("idx_customer_items_supplier")
        batch_op.drop_index("idx_customer_items_product")

    op.drop_table("customer_items")
    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.drop_index("idx_warehouses_type")
        batch_op.drop_index("idx_warehouses_code")

    op.drop_table("warehouses")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("idx_users_username")
        batch_op.drop_index("idx_users_email")
        batch_op.drop_index("idx_users_azure_oid")
        batch_op.drop_index("idx_users_auth_provider")
        batch_op.drop_index("idx_users_active", postgresql_where=sa.text("is_active = TRUE"))

    op.drop_table("users")
    with op.batch_alter_table("system_configs", schema=None) as batch_op:
        batch_op.drop_index("idx_system_configs_key")

    op.drop_table("system_configs")
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.drop_index("idx_suppliers_code")

    op.drop_table("suppliers")
    op.drop_table("seed_snapshots")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index("idx_roles_code")

    op.drop_table("roles")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index("idx_products_name")
        batch_op.drop_index("idx_products_code")

    op.drop_table("products")
    with op.batch_alter_table("forecast_history", schema=None) as batch_op:
        batch_op.drop_index("ix_forecast_history_key")

    op.drop_table("forecast_history")
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_index("idx_customers_code")

    op.drop_table("customers")
    with op.batch_alter_table("business_rules", schema=None) as batch_op:
        batch_op.drop_index("idx_business_rules_type")
        batch_op.drop_index("idx_business_rules_code")
        batch_op.drop_index(
            "idx_business_rules_active", postgresql_where=sa.text("is_active = TRUE")
        )

    op.drop_table("business_rules")
    with op.batch_alter_table("batch_jobs", schema=None) as batch_op:
        batch_op.drop_index("idx_batch_jobs_type")
        batch_op.drop_index("idx_batch_jobs_status")
        batch_op.drop_index("idx_batch_jobs_created")

    op.drop_table("batch_jobs")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
