"""remove_order_number_from_orders

Revision ID: 1fc6aeb192f2
Revises: 77d57966e3f7
Create Date: 2025-12-08 23:06:09.521897

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "1fc6aeb192f2"
down_revision = "77d57966e3f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # ビューの定義を更新（order_number削除）
    # 先にビューを更新して依存関係を解消する必要がある
    op.execute("DROP VIEW IF EXISTS public.v_order_line_details CASCADE")
    op.execute("""
    CREATE VIEW public.v_order_line_details AS
    SELECT
        o.id AS order_id,
        o.order_date,
        o.customer_id,
        c.customer_code,
        c.customer_name,
        ol.id AS line_id,
        ol.product_id,
        ol.delivery_date,
        ol.order_quantity,
        ol.unit,
        ol.delivery_place_id,
        ol.status AS line_status,
        ol.shipping_document_text,
        p.maker_part_code AS product_code,
        p.product_name,
        p.internal_unit AS product_internal_unit,
        p.external_unit AS product_external_unit,
        p.qty_per_internal_unit AS product_qty_per_internal_unit,
        dp.delivery_place_code,
        dp.delivery_place_name,
        dp.jiku_code,
        ci.external_product_code,
        s.supplier_name,
        COALESCE(SUM(a.allocated_quantity), 0) AS allocated_quantity
    FROM public.orders o
    LEFT JOIN public.customers c ON o.customer_id = c.id
    LEFT JOIN public.order_lines ol ON ol.order_id = o.id
    LEFT JOIN public.products p ON ol.product_id = p.id
    LEFT JOIN public.delivery_places dp ON ol.delivery_place_id = dp.id
    LEFT JOIN public.customer_items ci ON ci.customer_id = o.customer_id AND ci.product_id = ol.product_id
    LEFT JOIN public.suppliers s ON ci.supplier_id = s.id
    LEFT JOIN public.allocations a ON a.order_line_id = ol.id
    GROUP BY
        o.id, o.order_date, o.customer_id,
        c.customer_code, c.customer_name,
        ol.id, ol.product_id, ol.delivery_date, ol.order_quantity, ol.unit, ol.delivery_place_id, ol.status, ol.shipping_document_text,
        p.maker_part_code, p.product_name, p.internal_unit, p.external_unit, p.qty_per_internal_unit,
        dp.delivery_place_code, dp.delivery_place_name, dp.jiku_code,
        ci.external_product_code,
        s.supplier_name;
    """)

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint("uq_orders_order_number", type_="unique")
        batch_op.drop_column("order_number")

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("order_number", sa.VARCHAR(length=50), autoincrement=False, nullable=False)
        )
        batch_op.create_unique_constraint("uq_orders_order_number", ["order_number"])

    # ### end Alembic commands ###
    # ### end Alembic commands ###
