"""add_unit_columns

Revision ID: 2dca571dcd33
Revises: 977979c11ee5
Create Date: 2025-11-23 02:37:11.060216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dca571dcd33'
down_revision = '977979c11ee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('converted_quantity', sa.Numeric(precision=15, scale=3), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_unit', sa.String(length=20), server_default='CAN', nullable=False))
        batch_op.add_column(sa.Column('external_unit', sa.String(length=20), server_default='KG', nullable=False))
        batch_op.add_column(sa.Column('qty_per_internal_unit', sa.Numeric(precision=10, scale=4), server_default='1.0', nullable=False))

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('qty_per_internal_unit')
        batch_op.drop_column('external_unit')
        batch_op.drop_column('internal_unit')

    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_column('converted_quantity')

    # ### end Alembic commands ###
    # ### end Alembic commands ###
