"""merge calendar and test data heads

Revision ID: 36386d722bab
Revises: aa1b2c3d4e5f, ae0c76e46488
Create Date: 2026-01-18 15:25:10.142045

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "36386d722bab"
down_revision = ("aa1b2c3d4e5f", "ae0c76e46488")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
