"""add_coa_issue_date_to_allocation_suggestions

Revision ID: 3a0f933dd9bc
Revises: b20a425f473c
Create Date: 2026-02-03 15:04:59.808737

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "3a0f933dd9bc"
down_revision = "b20a425f473c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "allocation_suggestions",
        sa.Column("coa_issue_date", sa.Date(), nullable=True, comment="成績書発行日"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("allocation_suggestions", "coa_issue_date")
    # ### end Alembic commands ###
