"""Add cancel_reason column to orders

Revision ID: 3ee7b8597d75
Revises: p1q2r3s4t5u6
Create Date: 2026-01-10 12:37:22.996707

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "3ee7b8597d75"
down_revision = "p1q2r3s4t5u6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "cancel_reason",
                sa.String(length=255),
                nullable=True,
                comment="キャンセル・保留理由",
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("cancel_reason")
    # ### end Alembic commands ###
