"""add_shipping_master_tables

Revision ID: 40516792d7f0
Revises: 9086177e83a1
Create Date: 2026-01-20 13:05:16.390235

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "40516792d7f0"
down_revision = "9086177e83a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_register_rows",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("long_data_id", sa.BigInteger(), nullable=True),
        sa.Column("curated_master_id", sa.BigInteger(), nullable=True),
        sa.Column("task_date", sa.Date(), nullable=False),
        sa.Column("lot_no_1", sa.String(length=50), nullable=True),
        sa.Column("quantity_1", sa.Integer(), nullable=True),
        sa.Column("lot_no_2", sa.String(length=50), nullable=True),
        sa.Column("quantity_2", sa.Integer(), nullable=True),
        sa.Column("inbound_no", sa.String(length=50), nullable=True),
        sa.Column("shipping_date", sa.Date(), nullable=True),
        sa.Column("delivery_date", sa.Date(), nullable=True),
        sa.Column("delivery_quantity", sa.Integer(), nullable=True),
        sa.Column("item_no", sa.String(length=50), nullable=True),
        sa.Column("quantity_unit", sa.String(length=20), nullable=True),
        sa.Column("material_code", sa.String(length=50), nullable=True),
        sa.Column("jiku_code", sa.String(length=50), nullable=True),
        sa.Column("customer_part_no", sa.String(length=100), nullable=True),
        sa.Column("maker_part_no", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=20), server_default=sa.text("'OCR'"), nullable=False),
        sa.Column("shipping_slip_text", sa.Text(), nullable=True),
        sa.Column("customer_code", sa.String(length=50), nullable=True),
        sa.Column("customer_name", sa.String(length=100), nullable=True),
        sa.Column("supplier_code", sa.String(length=50), nullable=True),
        sa.Column("supplier_name", sa.String(length=100), nullable=True),
        sa.Column("shipping_warehouse_code", sa.String(length=50), nullable=True),
        sa.Column("shipping_warehouse_name", sa.String(length=100), nullable=True),
        sa.Column("delivery_place_code", sa.String(length=50), nullable=True),
        sa.Column("delivery_place_name", sa.String(length=200), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipping_master_raw",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=True),
        sa.Column("material_code", sa.String(length=50), nullable=True),
        sa.Column("jiku_code", sa.String(length=50), nullable=True),
        sa.Column("warehouse_code", sa.String(length=50), nullable=True),
        sa.Column("delivery_note_product_name", sa.Text(), nullable=True),
        sa.Column("customer_part_no", sa.String(length=100), nullable=True),
        sa.Column("maker_part_no", sa.String(length=100), nullable=True),
        sa.Column("order_flag", sa.String(length=20), nullable=True),
        sa.Column("maker_code", sa.String(length=50), nullable=True),
        sa.Column("maker_name", sa.String(length=100), nullable=True),
        sa.Column("supplier_code", sa.String(length=50), nullable=True),
        sa.Column("staff_name", sa.String(length=100), nullable=True),
        sa.Column("delivery_place_abbr", sa.String(length=100), nullable=True),
        sa.Column("delivery_place_code", sa.String(length=50), nullable=True),
        sa.Column("delivery_place_name", sa.String(length=200), nullable=True),
        sa.Column("shipping_warehouse", sa.String(length=100), nullable=True),
        sa.Column("shipping_slip_text", sa.Text(), nullable=True),
        sa.Column("transport_lt_days", sa.Integer(), nullable=True),
        sa.Column("order_existence", sa.String(length=20), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("import_batch_id", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipping_master_curated",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("raw_id", sa.BigInteger(), nullable=True),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("material_code", sa.String(length=50), nullable=False),
        sa.Column("jiku_code", sa.String(length=50), nullable=False),
        sa.Column("warehouse_code", sa.String(length=50), nullable=True),
        sa.Column("customer_name", sa.String(length=100), nullable=True),
        sa.Column("delivery_note_product_name", sa.Text(), nullable=True),
        sa.Column("customer_part_no", sa.String(length=100), nullable=True),
        sa.Column("maker_part_no", sa.String(length=100), nullable=True),
        sa.Column("maker_code", sa.String(length=50), nullable=True),
        sa.Column("maker_name", sa.String(length=100), nullable=True),
        sa.Column("supplier_code", sa.String(length=50), nullable=True),
        sa.Column("supplier_name", sa.String(length=100), nullable=True),
        sa.Column("delivery_place_code", sa.String(length=50), nullable=True),
        sa.Column("delivery_place_name", sa.String(length=200), nullable=True),
        sa.Column("shipping_warehouse_code", sa.String(length=50), nullable=True),
        sa.Column("shipping_warehouse_name", sa.String(length=100), nullable=True),
        sa.Column("shipping_slip_text", sa.Text(), nullable=True),
        sa.Column("transport_lt_days", sa.Integer(), nullable=True),
        sa.Column("has_order", sa.Boolean(), nullable=False),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("has_duplicate_warning", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["raw_id"], ["shipping_master_raw.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_code", "material_code", "jiku_code", name="uq_shipping_master_curated_key"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipping_master_curated")
    op.drop_table("shipping_master_raw")
    op.drop_table("order_register_rows")
    # ### end Alembic commands ###
