"""add_targeted_shipping_master_fields

Revision ID: 486eb9ffe359
Revises: 0085f02d2f77
Create Date: 2026-02-03 23:09:01.947203

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "486eb9ffe359"
down_revision = "0085f02d2f77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. customer_items
    op.add_column("customer_items", sa.Column("material_code", sa.String(length=50), nullable=True))
    op.add_column("customer_items", sa.Column("order_flag", sa.String(length=50), nullable=True))
    op.add_column(
        "customer_items", sa.Column("order_existence", sa.String(length=20), nullable=True)
    )

    # 2. supplier_items
    op.add_column("supplier_items", sa.Column("maker_code", sa.String(length=50), nullable=True))
    op.add_column("supplier_items", sa.Column("maker_name", sa.String(length=200), nullable=True))

    # 3. delivery_places
    op.add_column(
        "delivery_places", sa.Column("display_name", sa.String(length=200), nullable=True)
    )

    # 4. shipping_master_curated (Redundancy cleanup and Excel alignment)
    # Rename shipping_warehouse_code -> warehouse_code (after dropping existing warehouse_code if necessary, but here we just align)
    # Note: warehouse_code already exists, shipping_warehouse_code currently also exists.
    # We want to keep warehouse_code and remove shipping_warehouse_code.
    # And rename shipping_warehouse_name -> shipping_warehouse
    # Use raw SQL because op.drop_column doesn't support 'cascade' in all versions/dialects
    op.execute("ALTER TABLE shipping_master_curated DROP COLUMN shipping_warehouse_code CASCADE")
    op.alter_column(
        "shipping_master_curated", "shipping_warehouse_name", new_column_name="shipping_warehouse"
    )

    # Add staff_name, delivery_place_abbr, order_existence, order_flag
    op.add_column(
        "shipping_master_curated", sa.Column("staff_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "shipping_master_curated",
        sa.Column("delivery_place_abbr", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "shipping_master_curated", sa.Column("order_existence", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "shipping_master_curated", sa.Column("order_flag", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 4. shipping_master_curated
    op.drop_column("shipping_master_curated", "order_flag")
    op.drop_column("shipping_master_curated", "order_existence")
    op.drop_column("shipping_master_curated", "delivery_place_abbr")
    op.drop_column("shipping_master_curated", "staff_name")
    op.alter_column(
        "shipping_master_curated", "shipping_warehouse", new_column_name="shipping_warehouse_name"
    )
    op.add_column(
        "shipping_master_curated",
        sa.Column("shipping_warehouse_code", sa.String(length=50), nullable=True),
    )

    # 3. delivery_places
    op.drop_column("delivery_places", "display_name")

    # 2. supplier_items
    op.drop_column("supplier_items", "maker_name")
    op.drop_column("supplier_items", "maker_code")

    # 1. customer_items
    op.drop_column("customer_items", "order_existence")
    op.drop_column("customer_items", "order_flag")
    op.drop_column("customer_items", "material_code")
    # ### end Alembic commands ###
