"""add_forecast_id_and_priority_to_allocation_suggestions

Revision ID: 4cd63ead4106
Revises: 46e934ee58a8
Create Date: 2025-12-05 21:10:15.868559

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "4cd63ead4106"
down_revision = "46e934ee58a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "allocation_suggestions", sa.Column("forecast_id", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "allocation_suggestions",
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
    )
    op.create_index(
        "idx_allocation_suggestions_forecast",
        "allocation_suggestions",
        ["forecast_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "allocation_suggestions",
        "forecast_current",
        ["forecast_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "allocation_suggestions", type_="foreignkey")
    op.drop_index("idx_allocation_suggestions_forecast", table_name="allocation_suggestions")
    op.drop_column("allocation_suggestions", "priority")
    op.drop_column("allocation_suggestions", "forecast_id")
    # ### end Alembic commands ###
