"""merge_allocation_type

Revision ID: 4d2a15d9492f
Revises: add_allocation_type, d7898334ad53
Create Date: 2025-12-04 22:49:19.358512

"""

import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401


# revision identifiers, used by Alembic.
revision = "4d2a15d9492f"
down_revision = ("add_allocation_type", "d7898334ad53")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
