"""Add RPA jobs and SAP linkage support

Revision ID: 4e9ab10f6031
Revises: baseline_2026_01_27
Create Date: 2026-01-28 20:32:08.086328

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "4e9ab10f6031"
down_revision = "baseline_2026_01_27"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ocr_result_edits_completed",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("original_id", sa.BigInteger(), nullable=True),
        sa.Column("smartread_long_data_completed_id", sa.BigInteger(), nullable=False),
        sa.Column("lot_no_1", sa.String(length=100), nullable=True),
        sa.Column("quantity_1", sa.String(length=50), nullable=True),
        sa.Column("lot_no_2", sa.String(length=100), nullable=True),
        sa.Column("quantity_2", sa.String(length=50), nullable=True),
        sa.Column("inbound_no", sa.String(length=100), nullable=True),
        sa.Column("inbound_no_2", sa.String(length=100), nullable=True),
        sa.Column("shipping_date", sa.Date(), nullable=True),
        sa.Column("shipping_slip_text", sa.Text(), nullable=True),
        sa.Column("shipping_slip_text_edited", sa.Boolean(), nullable=False),
        sa.Column("jiku_code", sa.String(length=100), nullable=True),
        sa.Column("material_code", sa.String(length=100), nullable=True),
        sa.Column("delivery_quantity", sa.String(length=100), nullable=True),
        sa.Column("delivery_date", sa.String(length=100), nullable=True),
        sa.Column("sap_match_type", sa.String(length=50), nullable=True),
        sa.Column("sap_matched_zkdmat_b", sa.String(length=100), nullable=True),
        sa.Column("sap_supplier_code", sa.String(length=50), nullable=True),
        sa.Column("sap_supplier_name", sa.String(length=255), nullable=True),
        sa.Column("sap_qty_unit", sa.String(length=50), nullable=True),
        sa.Column("sap_maker_item", sa.String(length=100), nullable=True),
        sa.Column("process_status", sa.String(length=20), nullable=False),
        sa.Column("error_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rpa_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("timeout_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "smartread_long_data_completed",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("original_id", sa.BigInteger(), nullable=True),
        sa.Column("wide_data_id", sa.BigInteger(), nullable=True),
        sa.Column("config_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("task_date", sa.Date(), nullable=False),
        sa.Column("request_id_ref", sa.BigInteger(), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sap_order_no", sa.String(length=50), nullable=True),
        sa.Column(
            "completed_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("smartread_long_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rpa_job_id", sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column("sap_order_no", sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column("verification_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_smartread_long_data_rpa_job_id",
            "rpa_jobs",
            ["rpa_job_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("smartread_long_data", schema=None) as batch_op:
        batch_op.drop_constraint("fk_smartread_long_data_rpa_job_id", type_="foreignkey")
        batch_op.drop_column("verification_result")
        batch_op.drop_column("sap_order_no")
        batch_op.drop_column("rpa_job_id")

    op.drop_table("smartread_long_data_completed")
    op.drop_table("rpa_jobs")
    op.drop_table("ocr_result_edits_completed")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
