"""Merge multiple heads

Revision ID: 57a61e701331
Revises: 7f1d2c3b4a5e, baseline_2026_02_06
Create Date: 2026-02-06 23:28:29.024715

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "57a61e701331"
down_revision = ("7f1d2c3b4a5e", "baseline_2026_02_06")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
