"""add_optimistic_lock_to_orders

Revision ID: 6c8793735c3c
Revises: 3bf031f4ed27
Create Date: 2025-12-07 11:43:04.412644

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "6c8793735c3c"
down_revision = "3bf031f4ed27"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locked_by_user_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("locked_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("lock_expires_at", sa.DateTime(), nullable=True))
        batch_op.create_index(
            "idx_orders_lock_expires",
            ["lock_expires_at"],
            unique=False,
            postgresql_where=sa.text("lock_expires_at IS NOT NULL"),
        )
        batch_op.create_index("idx_orders_locked_by", ["locked_by_user_id"], unique=False)
        batch_op.create_foreign_key(
            None, "users", ["locked_by_user_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("product_suppliers", schema=None) as batch_op:
        batch_op.drop_index("ix_product_suppliers_product_id")
        batch_op.drop_index("ix_product_suppliers_supplier_id")

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_suppliers", schema=None) as batch_op:
        batch_op.create_index("ix_product_suppliers_supplier_id", ["supplier_id"], unique=False)
        batch_op.create_index("ix_product_suppliers_product_id", ["product_id"], unique=False)

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")  # type: ignore[arg-type]
        batch_op.drop_index("idx_orders_locked_by")
        batch_op.drop_index(
            "idx_orders_lock_expires", postgresql_where=sa.text("lock_expires_at IS NOT NULL")
        )
        batch_op.drop_column("lock_expires_at")
        batch_op.drop_column("locked_at")
        batch_op.drop_column("locked_by_user_id")

    # ### end Alembic commands ###
    # ### end Alembic commands ###
