"""Add smartread completion history tables

Revision ID: 70cdb27f5363
Revises: baseline_2026_01_27
Create Date: 2026-01-28 10:43:42.437044

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "70cdb27f5363"
down_revision = "baseline_2026_01_27"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ocr_result_edits_completed",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("original_id", sa.BigInteger(), nullable=True),
        sa.Column("smartread_long_data_completed_id", sa.BigInteger(), nullable=False),
        sa.Column("lot_no_1", sa.String(length=100), nullable=True),
        sa.Column("quantity_1", sa.String(length=50), nullable=True),
        sa.Column("lot_no_2", sa.String(length=100), nullable=True),
        sa.Column("quantity_2", sa.String(length=50), nullable=True),
        sa.Column("inbound_no", sa.String(length=100), nullable=True),
        sa.Column("inbound_no_2", sa.String(length=100), nullable=True),
        sa.Column("shipping_date", sa.Date(), nullable=True),
        sa.Column("shipping_slip_text", sa.Text(), nullable=True),
        sa.Column("shipping_slip_text_edited", sa.Boolean(), nullable=False),
        sa.Column("jiku_code", sa.String(length=100), nullable=True),
        sa.Column("material_code", sa.String(length=100), nullable=True),
        sa.Column("delivery_quantity", sa.String(length=100), nullable=True),
        sa.Column("delivery_date", sa.String(length=100), nullable=True),
        sa.Column("process_status", sa.String(length=20), nullable=False),
        sa.Column("error_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "smartread_long_data_completed",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("original_id", sa.BigInteger(), nullable=True),
        sa.Column("wide_data_id", sa.BigInteger(), nullable=True),
        sa.Column("config_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("task_date", sa.Date(), nullable=False),
        sa.Column("request_id_ref", sa.BigInteger(), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("supplier_items", schema=None) as batch_op:
        batch_op.alter_column(
            "maker_part_no",
            existing_type=sa.VARCHAR(length=100),
            nullable=False,
            existing_comment="メーカー品番（仕入先の品番）",
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("supplier_items", schema=None) as batch_op:
        batch_op.alter_column(
            "maker_part_no",
            existing_type=sa.VARCHAR(length=100),
            nullable=True,
            existing_comment="メーカー品番（仕入先の品番）",
        )

    op.drop_table("smartread_long_data_completed")
    op.drop_table("ocr_result_edits_completed")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
