"""drop legacy product columns

Revision ID: 7469e861ca23
Revises: phase3_monitor_view_update
Create Date: 2026-01-25 23:38:52.719105

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "7469e861ca23"
down_revision = "phase3_monitor_view_update"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("maker_item_code")
        batch_op.drop_column("customer_part_no")

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "customer_part_no",
                sa.VARCHAR(length=100),
                autoincrement=False,
                nullable=True,
                comment="先方品番（得意先の品番）",
            )
        )
        batch_op.add_column(
            sa.Column(
                "maker_item_code",
                sa.VARCHAR(length=100),
                autoincrement=False,
                nullable=True,
                comment="メーカー品番（仕入先の品番）",
            )
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###
