"""add_order_business_keys

Revision ID: 77d57966e3f7
Revises: 000000000000
Create Date: 2025-12-08 21:22:18.939340

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "77d57966e3f7"
down_revision = "000000000000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_groups",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column(
            "source_file_name", sa.String(length=255), nullable=True, comment="取り込み元ファイル名"
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_id", "product_id", "order_date", name="uq_order_groups_business_key"
        ),
    )
    with op.batch_alter_table("order_groups", schema=None) as batch_op:
        batch_op.create_index("idx_order_groups_customer", ["customer_id"], unique=False)
        batch_op.create_index("idx_order_groups_date", ["order_date"], unique=False)
        batch_op.create_index("idx_order_groups_product", ["product_id"], unique=False)

    with op.batch_alter_table("inbound_plans", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sap_po_number",
                sa.String(length=20),
                nullable=True,
                comment="SAP購買発注番号（業務キー）",
            )
        )
        batch_op.create_unique_constraint("uq_inbound_plans_sap_po_number", ["sap_po_number"])

    with op.batch_alter_table("order_lines", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "order_group_id",
                sa.BigInteger(),
                nullable=True,
                comment="受注グループへの参照（得意先×製品×受注日）",
            )
        )
        batch_op.add_column(
            sa.Column(
                "customer_order_no",
                sa.String(length=6),
                nullable=True,
                comment="得意先6桁受注番号（業務キー）",
            )
        )
        batch_op.add_column(
            sa.Column(
                "customer_order_line_no",
                sa.String(length=10),
                nullable=True,
                comment="得意先側行番号",
            )
        )
        batch_op.add_column(
            sa.Column(
                "sap_order_item_no",
                sa.String(length=6),
                nullable=True,
                comment="SAP明細番号（業務キー）",
            )
        )
        batch_op.alter_column(
            "sap_order_no",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=20),
            comment="SAP受注番号（業務キー）",
            existing_comment="SAP受注番号（登録済みの場合）",
            existing_nullable=True,
        )
        batch_op.create_index(
            "idx_order_lines_customer_order_no",
            ["customer_order_no"],
            unique=False,
            postgresql_where=sa.text("customer_order_no IS NOT NULL"),
        )
        batch_op.create_index("idx_order_lines_order_group", ["order_group_id"], unique=False)
        batch_op.create_unique_constraint(
            "uq_order_lines_customer_key", ["order_group_id", "customer_order_no"]
        )
        batch_op.create_foreign_key(
            "fk_order_lines_order_groups",
            "order_groups",
            ["order_group_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_lines", schema=None) as batch_op:
        batch_op.drop_constraint("fk_order_lines_order_groups", type_="foreignkey")
        batch_op.drop_constraint("uq_order_lines_customer_key", type_="unique")
        batch_op.drop_index("idx_order_lines_order_group")
        batch_op.drop_index(
            "idx_order_lines_customer_order_no",
            postgresql_where=sa.text("customer_order_no IS NOT NULL"),
        )
        batch_op.alter_column(
            "sap_order_no",
            existing_type=sa.String(length=20),
            type_=sa.VARCHAR(length=100),
            comment="SAP受注番号（登録済みの場合）",
            existing_comment="SAP受注番号（業務キー）",
            existing_nullable=True,
        )
        batch_op.drop_column("sap_order_item_no")
        batch_op.drop_column("customer_order_line_no")
        batch_op.drop_column("customer_order_no")
        batch_op.drop_column("order_group_id")

    with op.batch_alter_table("inbound_plans", schema=None) as batch_op:
        batch_op.drop_constraint("uq_inbound_plans_sap_po_number", type_="unique")
        batch_op.drop_column("sap_po_number")

    with op.batch_alter_table("order_groups", schema=None) as batch_op:
        batch_op.drop_index("idx_order_groups_product")
        batch_op.drop_index("idx_order_groups_date")
        batch_op.drop_index("idx_order_groups_customer")

    op.drop_table("order_groups")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
