"""merge_step4_columns_head

Revision ID: 7a50c98d743e
Revises: 24ab8ce1395d, g2h3i4j5k6l7
Create Date: 2025-12-21 02:38:43.594744

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "7a50c98d743e"
down_revision = ("24ab8ce1395d", "g2h3i4j5k6l7")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
