"""add_enable_db_browser_setting

Revision ID: 7b2ae6b36a5b
Revises: 777b9fe6c637
Create Date: 2026-01-26 20:42:04.809388

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "7b2ae6b36a5b"
down_revision = "777b9fe6c637"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "INSERT INTO system_configs (config_key, config_value, description) "
            "VALUES ('enable_db_browser', 'false', 'DBブラウザ（デバッグ用）の有効化フラグ') "
            "ON CONFLICT (config_key) DO NOTHING"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM system_configs WHERE config_key = 'enable_db_browser'"))
    # ### end Alembic commands ###
