"""add is_default to smartread_config

Revision ID: 8232dddf590e
Revises: cleanup_20260119
Create Date: 2026-01-19 17:21:30.889424

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "8232dddf590e"
down_revision = "cleanup_20260119"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("smartread_configs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False)
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("smartread_configs", schema=None) as batch_op:
        batch_op.drop_column("is_default")

    # ### end Alembic commands ###
    # ### end Alembic commands ###
