"""apply_views

Revision ID: 875526747bb6
Revises: 18dcee2f69a3
Create Date: 2025-11-27 19:33:55.877052

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '875526747bb6'
down_revision = '18dcee2f69a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply views from SQL files."""
    import os
    
    # Define paths to SQL files
    # Assuming the script is running from backend/ directory context or we can find relative to this file
    # But Alembic usually runs with CWD as backend/
    base_dir = os.getcwd()
    create_views_path = os.path.join(base_dir, 'sql', 'views', 'create_views.sql')
    additional_views_path = os.path.join(base_dir, 'sql', 'views', 'additional_views.sql')
    
    # Execute create_views.sql
    with open(create_views_path, encoding='utf-8') as f:
        op.execute(f.read())
        
    # Execute additional_views.sql
    with open(additional_views_path, encoding='utf-8') as f:
        op.execute(f.read())


def downgrade() -> None:
    """Revert views."""
    # Since create_views.sql handles DROP IF EXISTS, we can just drop the specific views we care about or leave it.
    # For safety, let's drop the main view we are introducing to be clean.
    op.execute("DROP VIEW IF EXISTS public.v_order_line_details CASCADE")
    # We could drop others too, but CASCADE on the main ones usually cleans up dependencies.
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
