"""merge supplier_items and delivery_date migrations

Revision ID: 975743e7c919
Revises: 271b5b7afd1d, g1h2i3j4k5l6
Create Date: 2026-01-25 11:17:37.483137

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "975743e7c919"
down_revision = "271b5b7afd1d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
