"""add_optimistic_lock_and_allocation_traces

Revision ID: 977979c11ee5
Revises: 87fb45f01bf8
Create Date: 2025-11-22 18:12:57.156632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '977979c11ee5'
down_revision = '87fb45f01bf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='スナップショット名'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='作成日時'),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='展開後の最終パラメータ（profile解決後）'),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='使用したプロファイル設定'),
    sa.Column('csv_dir', sa.Text(), nullable=True, comment='CSVエクスポートディレクトリ（オプション）'),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='生成結果のサマリ（件数、検証結果など）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocation_traces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_line_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('allocated_qty', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("decision IN ('adopted', 'rejected', 'partial')", name='chk_allocation_traces_decision'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allocation_traces', schema=None) as batch_op:
        batch_op.create_index('idx_allocation_traces_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_allocation_traces_lot', ['lot_id'], unique=False)
        batch_op.create_index('idx_allocation_traces_order_line', ['order_line_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_customer_code_key', type_='unique')
        batch_op.create_unique_constraint('uq_customers_customer_code', ['customer_code'])

    with op.batch_alter_table('delivery_places', schema=None) as batch_op:
        batch_op.drop_constraint('delivery_places_delivery_place_code_key', type_='unique')
        batch_op.create_unique_constraint('uq_delivery_places_code', ['delivery_place_code'])

    with op.batch_alter_table('forecast_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forecast_history_delivery_place', type_='foreignkey')
        batch_op.drop_constraint('fk_forecast_history_customer', type_='foreignkey')
        batch_op.drop_constraint('fk_forecast_history_product', type_='foreignkey')

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_order_number_key', type_='unique')
        batch_op.create_unique_constraint('uq_orders_order_number', ['order_number'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_maker_part_code_key', type_='unique')
        batch_op.create_unique_constraint('uq_products_maker_part_code', ['maker_part_code'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('roles_role_code_key', type_='unique')
        batch_op.create_unique_constraint('uq_roles_role_code', ['role_code'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint('suppliers_supplier_code_key', type_='unique')
        batch_op.create_unique_constraint('uq_suppliers_supplier_code', ['supplier_code'])

    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_constraint('system_configs_config_key_key', type_='unique')
        batch_op.create_unique_constraint('uq_system_configs_key', ['config_key'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('warehouses_warehouse_code_key', type_='unique')
        batch_op.create_unique_constraint('uq_warehouses_warehouse_code', ['warehouse_code'])

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_warehouses_warehouse_code', type_='unique')
        batch_op.create_unique_constraint('warehouses_warehouse_code_key', ['warehouse_code'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.create_unique_constraint('users_email_key', ['email'])

    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_system_configs_key', type_='unique')
        batch_op.create_unique_constraint('system_configs_config_key_key', ['config_key'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_suppliers_supplier_code', type_='unique')
        batch_op.create_unique_constraint('suppliers_supplier_code_key', ['supplier_code'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_roles_role_code', type_='unique')
        batch_op.create_unique_constraint('roles_role_code_key', ['role_code'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_products_maker_part_code', type_='unique')
        batch_op.create_unique_constraint('products_maker_part_code_key', ['maker_part_code'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_order_number', type_='unique')
        batch_op.create_unique_constraint('orders_order_number_key', ['order_number'])

    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_column('version_id')

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_column('version_id')

    with op.batch_alter_table('forecast_history', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_forecast_history_product', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_forecast_history_customer', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_forecast_history_delivery_place', 'delivery_places', ['delivery_place_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('delivery_places', schema=None) as batch_op:
        batch_op.drop_constraint('uq_delivery_places_code', type_='unique')
        batch_op.create_unique_constraint('delivery_places_delivery_place_code_key', ['delivery_place_code'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customers_customer_code', type_='unique')
        batch_op.create_unique_constraint('customers_customer_code_key', ['customer_code'])

    with op.batch_alter_table('allocation_traces', schema=None) as batch_op:
        batch_op.drop_index('idx_allocation_traces_order_line')
        batch_op.drop_index('idx_allocation_traces_lot')
        batch_op.drop_index('idx_allocation_traces_created_at')

    op.drop_table('allocation_traces')
    op.drop_table('seed_snapshots')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
