"""add system_client_logs table

Revision ID: 9decff574dcb
Revises: 561b887c8e22
Create Date: 2026-01-14 21:47:48.986333

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "9decff574dcb"
down_revision = "561b887c8e22"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("result_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "job_type IN ('allocation_suggestion', 'allocation_finalize', 'inventory_sync', 'data_import', 'report_generation')",
            name="chk_batch_jobs_type",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')", name="chk_batch_jobs_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("batch_jobs", schema=None) as batch_op:
        batch_op.create_index("idx_batch_jobs_created", ["created_at"], unique=False)
        batch_op.create_index("idx_batch_jobs_status", ["status"], unique=False)
        batch_op.create_index("idx_batch_jobs_type", ["job_type"], unique=False)

    op.create_table(
        "business_rules",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("rule_code", sa.String(length=50), nullable=False),
        sa.Column("rule_name", sa.String(length=100), nullable=False),
        sa.Column("rule_type", sa.String(length=50), nullable=False),
        sa.Column(
            "rule_parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "rule_type IN ('allocation', 'expiry_warning', 'kanban', 'inventory_sync_alert', 'other')",
            name="chk_business_rules_type",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_code"),
        sa.UniqueConstraint("rule_code", name="uq_business_rules_rule_code"),
    )
    with op.batch_alter_table("business_rules", schema=None) as batch_op:
        batch_op.create_index(
            "idx_business_rules_active",
            ["is_active"],
            unique=False,
            postgresql_where=sa.text("is_active = TRUE"),
        )
        batch_op.create_index("idx_business_rules_type", ["rule_type"], unique=False)

    op.create_table(
        "cloud_flow_configs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("config_key", sa.String(length=100), nullable=False),
        sa.Column("config_value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_key"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("contact_name", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("valid_to", sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_code", name="uq_customers_customer_code"),
    )
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.create_index("idx_customers_valid_to", ["valid_to"], unique=False)

    op.create_table(
        "forecast_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("forecast_date", sa.Date(), nullable=False),
        sa.Column("forecast_quantity", sa.Numeric(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("forecast_period", sa.String(length=7), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forecast_history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_forecast_history_key",
            ["customer_id", "delivery_place_id", "product_id"],
            unique=False,
        )

    op.create_table(
        "layer_code_mappings",
        sa.Column("layer_code", sa.String(length=50), nullable=False),
        sa.Column("maker_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("layer_code"),
    )
    with op.batch_alter_table("layer_code_mappings", schema=None) as batch_op:
        batch_op.create_index("idx_layer_code_mappings_maker", ["maker_name"], unique=False)

    op.create_table(
        "lot_reservation_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("reservation_id", sa.BigInteger(), nullable=False),
        sa.Column("operation", sa.String(length=10), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=True),
        sa.Column("source_type", sa.String(length=20), nullable=True),
        sa.Column("source_id", sa.BigInteger(), nullable=True),
        sa.Column("reserved_qty", sa.Numeric(precision=15, scale=3), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("sap_document_no", sa.String(length=20), nullable=True),
        sa.Column("old_lot_id", sa.BigInteger(), nullable=True),
        sa.Column("old_source_type", sa.String(length=20), nullable=True),
        sa.Column("old_source_id", sa.BigInteger(), nullable=True),
        sa.Column("old_reserved_qty", sa.Numeric(precision=15, scale=3), nullable=True),
        sa.Column("old_status", sa.String(length=20), nullable=True),
        sa.Column("old_sap_document_no", sa.String(length=20), nullable=True),
        sa.Column("changed_by", sa.String(length=100), nullable=True),
        sa.Column(
            "changed_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("change_reason", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "operation IN ('INSERT', 'UPDATE', 'DELETE')",
            name="chk_lot_reservation_history_operation",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lot_reservation_history", schema=None) as batch_op:
        batch_op.create_index(
            "idx_lot_reservation_history_changed_at", ["changed_at"], unique=False
        )
        batch_op.create_index("idx_lot_reservation_history_lot", ["lot_id"], unique=False)
        batch_op.create_index(
            "idx_lot_reservation_history_reservation", ["reservation_id"], unique=False
        )

    op.create_table(
        "products",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("maker_part_code", sa.String(length=100), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("base_unit", sa.String(length=20), nullable=False),
        sa.Column("consumption_limit_days", sa.Integer(), nullable=True),
        sa.Column("valid_to", sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("internal_unit", sa.String(length=20), server_default="CAN", nullable=False),
        sa.Column("external_unit", sa.String(length=20), server_default="KG", nullable=False),
        sa.Column(
            "qty_per_internal_unit",
            sa.Numeric(precision=10, scale=4),
            server_default="1.0",
            nullable=False,
        ),
        sa.Column(
            "customer_part_no",
            sa.String(length=100),
            nullable=True,
            comment="先方品番（得意先の品番）",
        ),
        sa.Column(
            "maker_item_code",
            sa.String(length=100),
            nullable=True,
            comment="メーカー品番（仕入先の品番）",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("maker_part_code", name="uq_products_maker_part_code"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index("idx_products_name", ["product_name"], unique=False)
        batch_op.create_index("idx_products_valid_to", ["valid_to"], unique=False)

    op.create_table(
        "roles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("role_code", sa.String(length=50), nullable=False),
        sa.Column("role_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_code", name="uq_roles_role_code"),
    )
    op.create_table(
        "seed_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False, comment="スナップショット名"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="作成日時"),
        sa.Column(
            "params_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
            comment="展開後の最終パラメータ（profile解決後）",
        ),
        sa.Column(
            "profile_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
            comment="使用したプロファイル設定",
        ),
        sa.Column(
            "csv_dir", sa.Text(), nullable=True, comment="CSVエクスポートディレクトリ（オプション）"
        ),
        sa.Column(
            "summary_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
            comment="生成結果のサマリ（件数、検証結果など）",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "smartread_configs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("api_key", sa.Text(), nullable=False),
        sa.Column("request_type", sa.String(length=50), nullable=False),
        sa.Column("template_ids", sa.Text(), nullable=True),
        sa.Column("export_type", sa.String(length=20), nullable=False),
        sa.Column("aggregation_type", sa.String(length=50), nullable=True),
        sa.Column("watch_dir", sa.Text(), nullable=True),
        sa.Column("export_dir", sa.Text(), nullable=True),
        sa.Column("input_exts", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_code", sa.String(length=50), nullable=False),
        sa.Column("supplier_name", sa.String(length=200), nullable=False),
        sa.Column("valid_to", sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supplier_code", name="uq_suppliers_supplier_code"),
    )
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.create_index("idx_suppliers_valid_to", ["valid_to"], unique=False)

    op.create_table(
        "system_configs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("config_key", sa.String(length=100), nullable=False),
        sa.Column("config_value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_key", name="uq_system_configs_key"),
    )
    with op.batch_alter_table("system_configs", schema=None) as batch_op:
        batch_op.create_index("idx_system_configs_key", ["config_key"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "auth_provider", sa.String(length=50), server_default=sa.text("'local'"), nullable=False
        ),
        sa.Column("azure_object_id", sa.String(length=100), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("azure_object_id"),
        sa.UniqueConstraint("azure_object_id", name="uq_users_azure_object_id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("username", name="uq_users_username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            "idx_users_active",
            ["is_active"],
            unique=False,
            postgresql_where=sa.text("is_active = TRUE"),
        )
        batch_op.create_index("idx_users_auth_provider", ["auth_provider"], unique=False)
        batch_op.create_index("idx_users_email", ["email"], unique=False)
        batch_op.create_index("idx_users_username", ["username"], unique=False)

    op.create_table(
        "warehouses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_code", sa.String(length=50), nullable=False),
        sa.Column("warehouse_name", sa.String(length=200), nullable=False),
        sa.Column("warehouse_type", sa.String(length=20), nullable=False),
        sa.Column(
            "default_transport_lead_time_days",
            sa.Integer(),
            nullable=True,
            comment="デフォルト輸送リードタイム（日）",
        ),
        sa.Column("valid_to", sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "warehouse_type IN ('internal', 'external', 'supplier')", name="chk_warehouse_type"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_code", name="uq_warehouses_warehouse_code"),
    )
    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.create_index("idx_warehouses_type", ["warehouse_type"], unique=False)
        batch_op.create_index("idx_warehouses_valid_to", ["valid_to"], unique=False)

    op.create_table(
        "cloud_flow_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("requested_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("result_message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cloud_flow_jobs", schema=None) as batch_op:
        batch_op.create_index("idx_cloud_flow_jobs_requested_at", ["requested_at"], unique=False)
        batch_op.create_index("idx_cloud_flow_jobs_status", ["status"], unique=False)
        batch_op.create_index("idx_cloud_flow_jobs_type", ["job_type"], unique=False)

    op.create_table(
        "customer_items",
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("external_product_code", sa.String(length=100), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=True),
        sa.Column("base_unit", sa.String(length=20), nullable=False),
        sa.Column("pack_unit", sa.String(length=20), nullable=True),
        sa.Column("pack_quantity", sa.Integer(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("shipping_document_template", sa.Text(), nullable=True),
        sa.Column("sap_notes", sa.Text(), nullable=True),
        sa.Column("maker_part_no", sa.String(length=100), nullable=True, comment="メーカー品番"),
        sa.Column(
            "order_category",
            sa.String(length=50),
            nullable=True,
            comment="発注区分（指示/かんばん等）",
        ),
        sa.Column(
            "is_procurement_required",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="発注の有無",
        ),
        sa.Column("shipping_slip_text", sa.Text(), nullable=True, comment="出荷票テキスト"),
        sa.Column("ocr_conversion_notes", sa.Text(), nullable=True, comment="OCR変換用備考"),
        sa.Column(
            "sap_supplier_code",
            sa.String(length=50),
            nullable=True,
            comment="SAP仕入先コード（キャッシュ）",
        ),
        sa.Column(
            "sap_warehouse_code",
            sa.String(length=50),
            nullable=True,
            comment="SAP倉庫コード（キャッシュ）",
        ),
        sa.Column(
            "sap_shipping_warehouse",
            sa.String(length=50),
            nullable=True,
            comment="SAP出荷倉庫（キャッシュ）",
        ),
        sa.Column("sap_uom", sa.String(length=20), nullable=True, comment="SAP単位（キャッシュ）"),
        sa.Column("valid_to", sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("customer_id", "external_product_code"),
    )
    with op.batch_alter_table("customer_items", schema=None) as batch_op:
        batch_op.create_index("idx_customer_items_order_category", ["order_category"], unique=False)
        batch_op.create_index("idx_customer_items_product", ["product_id"], unique=False)
        batch_op.create_index("idx_customer_items_supplier", ["supplier_id"], unique=False)
        batch_op.create_index("idx_customer_items_valid_to", ["valid_to"], unique=False)

    op.create_table(
        "delivery_places",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("jiku_code", sa.String(length=50), server_default="", nullable=False),
        sa.Column("delivery_place_code", sa.String(length=50), nullable=False),
        sa.Column("delivery_place_name", sa.String(length=200), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("valid_to", sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_place_code", name="uq_delivery_places_code"),
    )
    with op.batch_alter_table("delivery_places", schema=None) as batch_op:
        batch_op.create_index("idx_delivery_places_customer", ["customer_id"], unique=False)
        batch_op.create_index("idx_delivery_places_valid_to", ["valid_to"], unique=False)

    op.create_table(
        "inbound_plans",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("plan_number", sa.String(length=50), nullable=False),
        sa.Column(
            "sap_po_number",
            sa.String(length=20),
            nullable=True,
            comment="SAP購買発注番号（業務キー）",
        ),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("planned_arrival_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'planned'"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('planned','partially_received','received','cancelled')",
            name="chk_inbound_plans_status",
        ),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_number", name="uq_inbound_plans_plan_number"),
        sa.UniqueConstraint("sap_po_number"),
        sa.UniqueConstraint("sap_po_number", name="uq_inbound_plans_sap_po_number"),
    )
    with op.batch_alter_table("inbound_plans", schema=None) as batch_op:
        batch_op.create_index("idx_inbound_plans_date", ["planned_arrival_date"], unique=False)
        batch_op.create_index("idx_inbound_plans_status", ["status"], unique=False)
        batch_op.create_index("idx_inbound_plans_supplier", ["supplier_id"], unique=False)

    op.create_table(
        "master_change_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("table_name", sa.String(length=50), nullable=False),
        sa.Column("record_id", sa.BigInteger(), nullable=False),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column(
            "old_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "new_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("changed_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "changed_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "change_type IN ('insert', 'update', 'delete')", name="chk_master_change_logs_type"
        ),
        sa.ForeignKeyConstraint(["changed_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("master_change_logs", schema=None) as batch_op:
        batch_op.create_index("idx_master_change_logs_changed", ["changed_at"], unique=False)
        batch_op.create_index("idx_master_change_logs_record", ["record_id"], unique=False)
        batch_op.create_index("idx_master_change_logs_table", ["table_name"], unique=False)
        batch_op.create_index("idx_master_change_logs_user", ["changed_by"], unique=False)

    op.create_table(
        "operation_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.String(length=50), nullable=False),
        sa.Column("target_table", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "changes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "operation_type IN ('create', 'update', 'delete', 'login', 'logout', 'export')",
            name="chk_operation_logs_type",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("operation_logs", schema=None) as batch_op:
        batch_op.create_index("idx_operation_logs_created", ["created_at"], unique=False)
        batch_op.create_index("idx_operation_logs_table", ["target_table"], unique=False)
        batch_op.create_index("idx_operation_logs_type", ["operation_type"], unique=False)
        batch_op.create_index("idx_operation_logs_user", ["user_id"], unique=False)

    op.create_table(
        "order_groups",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column(
            "source_file_name", sa.String(length=255), nullable=True, comment="取り込み元ファイル名"
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_id", "product_id", "order_date", name="uq_order_groups_business_key"
        ),
    )
    with op.batch_alter_table("order_groups", schema=None) as batch_op:
        batch_op.create_index("idx_order_groups_customer", ["customer_id"], unique=False)
        batch_op.create_index("idx_order_groups_date", ["order_date"], unique=False)
        batch_op.create_index("idx_order_groups_product", ["product_id"], unique=False)

    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("locked_by_user_id", sa.Integer(), nullable=True),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("lock_expires_at", sa.DateTime(), nullable=True),
        sa.Column(
            "ocr_source_filename",
            sa.String(length=255),
            nullable=True,
            comment="OCR取込元ファイル名",
        ),
        sa.Column(
            "cancel_reason", sa.String(length=255), nullable=True, comment="キャンセル・保留理由"
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["locked_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index("idx_orders_customer", ["customer_id"], unique=False)
        batch_op.create_index("idx_orders_date", ["order_date"], unique=False)
        batch_op.create_index(
            "idx_orders_lock_expires",
            ["lock_expires_at"],
            unique=False,
            postgresql_where=sa.text("lock_expires_at IS NOT NULL"),
        )
        batch_op.create_index("idx_orders_locked_by", ["locked_by_user_id"], unique=False)

    op.create_table(
        "product_mappings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_part_code", sa.String(length=100), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("base_unit", sa.String(length=20), nullable=False),
        sa.Column("pack_unit", sa.String(length=20), nullable=True),
        sa.Column("pack_quantity", sa.Integer(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("valid_to", sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_id",
            "customer_part_code",
            "supplier_id",
            name="uq_product_mappings_cust_part_supp",
        ),
    )
    with op.batch_alter_table("product_mappings", schema=None) as batch_op:
        batch_op.create_index("idx_product_mappings_customer", ["customer_id"], unique=False)
        batch_op.create_index("idx_product_mappings_product", ["product_id"], unique=False)
        batch_op.create_index("idx_product_mappings_supplier", ["supplier_id"], unique=False)
        batch_op.create_index("idx_product_mappings_valid_to", ["valid_to"], unique=False)

    op.create_table(
        "product_suppliers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("valid_to", sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "supplier_id", name="uq_product_supplier"),
    )
    with op.batch_alter_table("product_suppliers", schema=None) as batch_op:
        batch_op.create_index("idx_product_suppliers_valid_to", ["valid_to"], unique=False)
        batch_op.create_index(
            "uq_product_primary_supplier",
            ["product_id"],
            unique=True,
            postgresql_where=sa.text("is_primary = true"),
        )

    op.create_table(
        "product_uom_conversions",
        sa.Column("conversion_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("external_unit", sa.String(length=20), nullable=False),
        sa.Column("factor", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("valid_to", sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversion_id"),
        sa.UniqueConstraint("product_id", "external_unit", name="uq_uom_conversions_product_unit"),
    )
    with op.batch_alter_table("product_uom_conversions", schema=None) as batch_op:
        batch_op.create_index("idx_product_uom_conversions_valid_to", ["valid_to"], unique=False)

    op.create_table(
        "rpa_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "rpa_type",
            sa.String(length=50),
            server_default="material_delivery_note",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=30), server_default="downloaded", nullable=False),
        sa.Column("data_start_date", sa.Date(), nullable=True),
        sa.Column("data_end_date", sa.Date(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("started_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("step2_executed_at", sa.DateTime(), nullable=True),
        sa.Column("step2_executed_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("external_done_at", sa.DateTime(), nullable=True),
        sa.Column("external_done_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("step4_executed_at", sa.DateTime(), nullable=True),
        sa.Column("customer_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["external_done_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["started_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["step2_executed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rpa_runs", schema=None) as batch_op:
        batch_op.create_index("idx_rpa_runs_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_rpa_runs_customer_id", ["customer_id"], unique=False)
        batch_op.create_index("idx_rpa_runs_status", ["status"], unique=False)
        batch_op.create_index("idx_rpa_runs_type", ["rpa_type"], unique=False)

    op.create_table(
        "system_client_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("level", sa.String(length=20), server_default=sa.text("'info'"), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("system_client_logs", schema=None) as batch_op:
        batch_op.create_index("idx_system_client_logs_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_system_client_logs_user_id", ["user_id"], unique=False)

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.create_index("idx_user_roles_role", ["role_id"], unique=False)
        batch_op.create_index("idx_user_roles_user", ["user_id"], unique=False)

    op.create_table(
        "user_supplier_assignments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "supplier_id", name="uq_user_supplier_assignments_user_supplier"
        ),
    )
    with op.batch_alter_table("user_supplier_assignments", schema=None) as batch_op:
        batch_op.create_index(
            "idx_user_supplier_assignments_primary",
            ["is_primary"],
            unique=False,
            postgresql_where=sa.text("is_primary = TRUE"),
        )
        batch_op.create_index(
            "idx_user_supplier_assignments_supplier", ["supplier_id"], unique=False
        )
        batch_op.create_index("idx_user_supplier_assignments_user", ["user_id"], unique=False)
        batch_op.create_index(
            "uq_user_supplier_primary_per_supplier",
            ["supplier_id"],
            unique=True,
            postgresql_where=sa.text("is_primary = TRUE"),
        )

    op.create_table(
        "customer_item_delivery_settings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("external_product_code", sa.String(length=100), nullable=False),
        sa.Column(
            "delivery_place_id",
            sa.BigInteger(),
            nullable=True,
            comment="納入先（NULLの場合はデフォルト設定）",
        ),
        sa.Column(
            "jiku_code",
            sa.String(length=50),
            nullable=True,
            comment="次区コード（NULLの場合は全次区共通）",
        ),
        sa.Column("shipment_text", sa.Text(), nullable=True, comment="出荷表テキスト（SAP連携用）"),
        sa.Column("packing_note", sa.Text(), nullable=True, comment="梱包・注意書き"),
        sa.Column("lead_time_days", sa.Integer(), nullable=True, comment="リードタイム（日）"),
        sa.Column(
            "is_default",
            sa.Boolean(),
            server_default="FALSE",
            nullable=False,
            comment="デフォルト設定フラグ",
        ),
        sa.Column("valid_from", sa.Date(), nullable=True, comment="有効開始日"),
        sa.Column("valid_to", sa.Date(), nullable=True, comment="有効終了日"),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "external_product_code"],
            ["customer_items.customer_id", "customer_items.external_product_code"],
            name="fk_customer_item_delivery_settings_customer_item",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_id",
            "external_product_code",
            "delivery_place_id",
            "jiku_code",
            name="uq_customer_item_delivery_settings",
        ),
    )
    with op.batch_alter_table("customer_item_delivery_settings", schema=None) as batch_op:
        batch_op.create_index(
            "idx_cids_customer_item", ["customer_id", "external_product_code"], unique=False
        )
        batch_op.create_index("idx_cids_delivery_place", ["delivery_place_id"], unique=False)
        batch_op.create_index("idx_cids_jiku_code", ["jiku_code"], unique=False)

    op.create_table(
        "customer_item_jiku_mappings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("external_product_code", sa.String(length=100), nullable=False),
        sa.Column("jiku_code", sa.String(length=50), nullable=False),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="FALSE", nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "external_product_code"],
            ["customer_items.customer_id", "customer_items.external_product_code"],
            name="fk_customer_item_jiku_mappings_customer_item",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_id", "external_product_code", "jiku_code", name="uq_customer_item_jiku"
        ),
    )
    op.create_table(
        "forecast_current",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("forecast_date", sa.Date(), nullable=False),
        sa.Column("forecast_quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("forecast_period", sa.String(length=7), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forecast_current", schema=None) as batch_op:
        batch_op.create_index(
            "idx_forecast_current_unique",
            ["customer_id", "delivery_place_id", "product_id"],
            unique=False,
        )
        batch_op.create_index(
            "ux_forecast_current_unique",
            ["customer_id", "delivery_place_id", "product_id", "forecast_date", "forecast_period"],
            unique=True,
        )

    op.create_table(
        "inbound_plan_lines",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("inbound_plan_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("planned_quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["inbound_plan_id"], ["inbound_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inbound_plan_lines", schema=None) as batch_op:
        batch_op.create_index("idx_inbound_plan_lines_plan", ["inbound_plan_id"], unique=False)
        batch_op.create_index("idx_inbound_plan_lines_product", ["product_id"], unique=False)

    op.create_table(
        "order_lines",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "order_group_id",
            sa.BigInteger(),
            nullable=True,
            comment="受注グループへの参照（得意先×製品×受注日）",
        ),
        sa.Column(
            "product_id",
            sa.BigInteger(),
            nullable=True,
            comment="製品ID（OCR取込時はNULL可、変換後に設定）",
        ),
        sa.Column(
            "external_product_code",
            sa.String(length=100),
            nullable=True,
            comment="OCR元の先方品番（変換前の生データ）",
        ),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column("order_quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("converted_quantity", sa.Numeric(precision=15, scale=3), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "customer_order_no",
            sa.String(length=6),
            nullable=True,
            comment="得意先6桁受注番号（業務キー）",
        ),
        sa.Column(
            "customer_order_line_no", sa.String(length=10), nullable=True, comment="得意先側行番号"
        ),
        sa.Column(
            "sap_order_no", sa.String(length=20), nullable=True, comment="SAP受注番号（業務キー）"
        ),
        sa.Column(
            "sap_order_item_no",
            sa.String(length=6),
            nullable=True,
            comment="SAP明細番号（業務キー）",
        ),
        sa.Column("shipping_document_text", sa.Text(), nullable=True, comment="出荷表テキスト"),
        sa.Column(
            "order_type",
            sa.String(length=20),
            server_default=sa.text("'ORDER'"),
            nullable=False,
            comment="需要種別: FORECAST_LINKED / KANBAN / SPOT / ORDER",
        ),
        sa.Column(
            "forecast_reference",
            sa.String(length=100),
            nullable=True,
            comment="Forecast business key reference (replaces forecast_id FK)",
        ),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "order_type IN ('FORECAST_LINKED', 'KANBAN', 'SPOT', 'ORDER')",
            name="chk_order_lines_order_type",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'allocated', 'shipped', 'completed', 'cancelled', 'on_hold')",
            name="chk_order_lines_status",
        ),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_group_id"], ["order_groups.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_group_id", "customer_order_no", name="uq_order_lines_customer_key"
        ),
    )
    with op.batch_alter_table("order_lines", schema=None) as batch_op:
        batch_op.create_index(
            "idx_order_lines_customer_order_no",
            ["customer_order_no"],
            unique=False,
            postgresql_where=sa.text("customer_order_no IS NOT NULL"),
        )
        batch_op.create_index("idx_order_lines_date", ["delivery_date"], unique=False)
        batch_op.create_index("idx_order_lines_delivery_place", ["delivery_place_id"], unique=False)
        batch_op.create_index(
            "idx_order_lines_forecast_reference",
            ["forecast_reference"],
            unique=False,
            postgresql_where=sa.text("forecast_reference IS NOT NULL"),
        )
        batch_op.create_index("idx_order_lines_order", ["order_id"], unique=False)
        batch_op.create_index("idx_order_lines_order_group", ["order_group_id"], unique=False)
        batch_op.create_index("idx_order_lines_order_type", ["order_type"], unique=False)
        batch_op.create_index("idx_order_lines_product", ["product_id"], unique=False)
        batch_op.create_index(
            "idx_order_lines_sap_order_no",
            ["sap_order_no"],
            unique=False,
            postgresql_where=sa.text("sap_order_no IS NOT NULL"),
        )
        batch_op.create_index("idx_order_lines_status", ["status"], unique=False)

    op.create_table(
        "rpa_run_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("row_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("jiku_code", sa.String(length=50), nullable=True),
        sa.Column("layer_code", sa.String(length=50), nullable=True),
        sa.Column("external_product_code", sa.String(length=100), nullable=True),
        sa.Column("delivery_date", sa.Date(), nullable=True),
        sa.Column("delivery_quantity", sa.Integer(), nullable=True),
        sa.Column("shipping_vehicle", sa.String(length=50), nullable=True),
        sa.Column("issue_flag", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("complete_flag", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("match_result", sa.Boolean(), nullable=True),
        sa.Column("sap_registered", sa.Boolean(), nullable=True),
        sa.Column("order_no", sa.String(length=100), nullable=True),
        sa.Column("lock_flag", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("item_no", sa.String(length=100), nullable=True),
        sa.Column("lot_no", sa.String(length=100), nullable=True),
        sa.Column("result_status", sa.String(length=20), nullable=True),
        sa.Column("processing_started_at", sa.DateTime(), nullable=True),
        sa.Column(
            "complement_customer_id",
            sa.BigInteger(),
            nullable=True,
            comment="参照したマスタのcustomer_id",
        ),
        sa.Column(
            "complement_external_product_code",
            sa.String(length=100),
            nullable=True,
            comment="参照したマスタのexternal_product_code",
        ),
        sa.Column(
            "complement_match_type",
            sa.String(length=10),
            nullable=True,
            comment="検索種別（exact: 完全一致, prefix: 前方一致）",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["run_id"], ["rpa_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rpa_run_items", schema=None) as batch_op:
        batch_op.create_index("idx_rpa_run_items_run_id", ["run_id"], unique=False)
        batch_op.create_index("idx_rpa_run_items_run_row", ["run_id", "row_no"], unique=True)
        batch_op.create_index(
            "idx_rri_complement_master",
            ["complement_customer_id", "complement_external_product_code"],
            unique=False,
        )

    op.create_table(
        "warehouse_delivery_routes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "product_id",
            sa.BigInteger(),
            nullable=True,
            comment="品番（NULLの場合は経路デフォルト）",
        ),
        sa.Column(
            "transport_lead_time_days",
            sa.Integer(),
            nullable=False,
            comment="輸送リードタイム（日）",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="有効フラグ",
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="備考"),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("warehouse_delivery_routes", schema=None) as batch_op:
        batch_op.create_index("idx_wdr_active", ["is_active"], unique=False)
        batch_op.create_index("idx_wdr_delivery_place", ["delivery_place_id"], unique=False)
        batch_op.create_index("idx_wdr_product", ["product_id"], unique=False)
        batch_op.create_index("idx_wdr_warehouse", ["warehouse_id"], unique=False)

    op.create_table(
        "expected_lots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("inbound_plan_line_id", sa.BigInteger(), nullable=False),
        sa.Column("expected_lot_number", sa.String(length=100), nullable=True),
        sa.Column("expected_quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("expected_expiry_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["inbound_plan_line_id"], ["inbound_plan_lines.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expected_lots", schema=None) as batch_op:
        batch_op.create_index("idx_expected_lots_line", ["inbound_plan_line_id"], unique=False)
        batch_op.create_index("idx_expected_lots_number", ["expected_lot_number"], unique=False)

    op.create_table(
        "lots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("lot_number", sa.String(length=100), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("warehouse_id", sa.BigInteger(), nullable=False),
        sa.Column("supplier_id", sa.BigInteger(), nullable=True),
        sa.Column("expected_lot_id", sa.BigInteger(), nullable=True),
        sa.Column("received_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "current_quantity",
            sa.Numeric(precision=15, scale=3),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("lock_reason", sa.Text(), nullable=True),
        sa.Column(
            "locked_quantity",
            sa.Numeric(precision=15, scale=3),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "inspection_status",
            sa.String(length=20),
            server_default=sa.text("'not_required'"),
            nullable=False,
        ),
        sa.Column("inspection_date", sa.Date(), nullable=True),
        sa.Column("inspection_cert_number", sa.String(length=100), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "origin_type", sa.String(length=20), server_default=sa.text("'adhoc'"), nullable=False
        ),
        sa.Column("origin_reference", sa.String(length=255), nullable=True),
        sa.Column(
            "temporary_lot_key", sa.UUID(), nullable=True, comment="仮入庫時の一意識別キー（UUID）"
        ),
        sa.CheckConstraint(
            "inspection_status IN ('not_required','pending','passed','failed')",
            name="chk_lots_inspection_status",
        ),
        sa.CheckConstraint(
            "origin_type IN ('order','forecast','sample','safety_stock','adhoc')",
            name="chk_lots_origin_type",
        ),
        sa.CheckConstraint(
            "status IN ('active','depleted','expired','quarantine','locked')",
            name="chk_lots_status",
        ),
        sa.CheckConstraint("current_quantity >= 0", name="chk_lots_current_quantity"),
        sa.CheckConstraint("locked_quantity >= 0", name="chk_lots_locked_quantity"),
        sa.ForeignKeyConstraint(["expected_lot_id"], ["expected_lots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "lot_number", "product_id", "warehouse_id", name="uq_lots_number_product_warehouse"
        ),
        sa.UniqueConstraint("temporary_lot_key"),
        sa.UniqueConstraint("temporary_lot_key", name="uq_lots_temporary_lot_key"),
    )
    with op.batch_alter_table("lots", schema=None) as batch_op:
        batch_op.create_index(
            "idx_lots_expiry_date",
            ["expiry_date"],
            unique=False,
            postgresql_where=sa.text("expiry_date IS NOT NULL"),
        )
        batch_op.create_index("idx_lots_number", ["lot_number"], unique=False)
        batch_op.create_index("idx_lots_origin_type", ["origin_type"], unique=False)
        batch_op.create_index(
            "idx_lots_product_warehouse", ["product_id", "warehouse_id"], unique=False
        )
        batch_op.create_index("idx_lots_status", ["status"], unique=False)
        batch_op.create_index("idx_lots_supplier", ["supplier_id"], unique=False)
        batch_op.create_index(
            "idx_lots_temporary_lot_key",
            ["temporary_lot_key"],
            unique=False,
            postgresql_where=sa.text("temporary_lot_key IS NOT NULL"),
        )
        batch_op.create_index("idx_lots_warehouse", ["warehouse_id"], unique=False)

    op.create_table(
        "adjustments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=False),
        sa.Column("adjustment_type", sa.String(length=20), nullable=False),
        sa.Column("adjusted_quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("adjusted_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "adjusted_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "adjustment_type IN ('physical_count','damage','loss','found','other')",
            name="chk_adjustments_type",
        ),
        sa.ForeignKeyConstraint(["adjusted_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("adjustments", schema=None) as batch_op:
        batch_op.create_index("idx_adjustments_date", ["adjusted_at"], unique=False)
        batch_op.create_index("idx_adjustments_lot", ["lot_id"], unique=False)

    op.create_table(
        "allocation_suggestions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_line_id", sa.BigInteger(), nullable=True),
        sa.Column("forecast_period", sa.String(length=7), nullable=False),
        sa.Column("forecast_id", sa.BigInteger(), nullable=True),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("allocation_type", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["forecast_id"], ["forecast_current.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("allocation_suggestions", schema=None) as batch_op:
        batch_op.create_index("idx_allocation_suggestions_customer", ["customer_id"], unique=False)
        batch_op.create_index("idx_allocation_suggestions_forecast", ["forecast_id"], unique=False)
        batch_op.create_index("idx_allocation_suggestions_lot", ["lot_id"], unique=False)
        batch_op.create_index(
            "idx_allocation_suggestions_period", ["forecast_period"], unique=False
        )
        batch_op.create_index("idx_allocation_suggestions_product", ["product_id"], unique=False)

    op.create_table(
        "allocation_traces",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_line_id", sa.BigInteger(), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=True),
        sa.Column("score", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("allocated_qty", sa.Numeric(precision=15, scale=3), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "decision IN ('adopted', 'rejected', 'partial')", name="chk_allocation_traces_decision"
        ),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["order_line_id"], ["order_lines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("allocation_traces", schema=None) as batch_op:
        batch_op.create_index("idx_allocation_traces_created_at", ["created_at"], unique=False)
        batch_op.create_index("idx_allocation_traces_lot", ["lot_id"], unique=False)
        batch_op.create_index("idx_allocation_traces_order_line", ["order_line_id"], unique=False)

    op.create_table(
        "lot_reservations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source_type",
            sa.String(length=20),
            nullable=False,
            comment="Reservation source: 'forecast' | 'order' | 'manual'",
        ),
        sa.Column(
            "source_id",
            sa.BigInteger(),
            nullable=True,
            comment="ID of the source entity (order_line_id, forecast_group_id, etc.)",
        ),
        sa.Column(
            "reserved_qty",
            sa.Numeric(precision=15, scale=3),
            nullable=False,
            comment="Reserved quantity (must be positive)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
            comment="Reservation status: 'temporary' | 'active' | 'confirmed' | 'released'",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True, comment="Timestamp of last update"),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            nullable=True,
            comment="Expiration time for temporary reservations",
        ),
        sa.Column(
            "confirmed_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp when reservation was confirmed",
        ),
        sa.Column(
            "confirmed_by",
            sa.String(length=50),
            nullable=True,
            comment="User who confirmed the reservation",
        ),
        sa.Column(
            "released_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp when reservation was released",
        ),
        sa.Column(
            "cancel_reason",
            sa.String(length=50),
            nullable=True,
            comment="Reason for cancellation (input_error, wrong_quantity, etc.)",
        ),
        sa.Column(
            "cancel_note",
            sa.String(length=500),
            nullable=True,
            comment="Additional notes for cancellation",
        ),
        sa.Column(
            "cancelled_by",
            sa.String(length=50),
            nullable=True,
            comment="User who cancelled the reservation",
        ),
        sa.Column(
            "sap_document_no",
            sa.String(length=20),
            nullable=True,
            comment="SAP document number (set on successful SAP registration)",
        ),
        sa.Column(
            "sap_registered_at",
            sa.DateTime(),
            nullable=True,
            comment="Timestamp when reservation was registered in SAP",
        ),
        sa.CheckConstraint(
            "source_type IN ('forecast', 'order', 'manual')",
            name="chk_lot_reservations_source_type",
        ),
        sa.CheckConstraint(
            "status IN ('temporary', 'active', 'confirmed', 'released')",
            name="chk_lot_reservations_status",
        ),
        sa.CheckConstraint("reserved_qty > 0", name="chk_lot_reservations_qty_positive"),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lot_reservations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_lot_reservations_expires_at",
            ["expires_at"],
            unique=False,
            postgresql_where=sa.text("expires_at IS NOT NULL"),
        )
        batch_op.create_index("idx_lot_reservations_lot_status", ["lot_id", "status"], unique=False)
        batch_op.create_index(
            "idx_lot_reservations_source", ["source_type", "source_id"], unique=False
        )
        batch_op.create_index("idx_lot_reservations_status", ["status"], unique=False)

    op.create_table(
        "stock_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=False),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("quantity_change", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("quantity_after", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "transaction_date",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "transaction_type IN ('inbound','allocation','shipment','adjustment','return','allocation_hold','allocation_release','withdrawal')",
            name="chk_stock_history_type",
        ),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_history", schema=None) as batch_op:
        batch_op.create_index("idx_stock_history_date", ["transaction_date"], unique=False)
        batch_op.create_index("idx_stock_history_lot", ["lot_id"], unique=False)
        batch_op.create_index("idx_stock_history_type", ["transaction_type"], unique=False)

    op.create_table(
        "withdrawals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("lot_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("withdrawal_type", sa.String(length=20), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=True),
        sa.Column("delivery_place_id", sa.BigInteger(), nullable=True),
        sa.Column("ship_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("reference_number", sa.String(length=100), nullable=True),
        sa.Column("withdrawn_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "withdrawn_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_by", sa.BigInteger(), nullable=True),
        sa.Column("cancel_reason", sa.String(length=50), nullable=True),
        sa.Column("cancel_note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "withdrawal_type IN ('order_manual','internal_use','disposal','return','sample','other')",
            name="chk_withdrawals_type",
        ),
        sa.CheckConstraint("quantity > 0", name="chk_withdrawals_quantity"),
        sa.ForeignKeyConstraint(["cancelled_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["delivery_place_id"], ["delivery_places.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["lot_id"], ["lots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["withdrawn_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("withdrawals", schema=None) as batch_op:
        batch_op.create_index("idx_withdrawals_customer", ["customer_id"], unique=False)
        batch_op.create_index("idx_withdrawals_date", ["ship_date"], unique=False)
        batch_op.create_index("idx_withdrawals_lot", ["lot_id"], unique=False)
        batch_op.create_index("idx_withdrawals_type", ["withdrawal_type"], unique=False)

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("withdrawals", schema=None) as batch_op:
        batch_op.drop_index("idx_withdrawals_type")
        batch_op.drop_index("idx_withdrawals_lot")
        batch_op.drop_index("idx_withdrawals_date")
        batch_op.drop_index("idx_withdrawals_customer")

    op.drop_table("withdrawals")
    with op.batch_alter_table("stock_history", schema=None) as batch_op:
        batch_op.drop_index("idx_stock_history_type")
        batch_op.drop_index("idx_stock_history_lot")
        batch_op.drop_index("idx_stock_history_date")

    op.drop_table("stock_history")
    with op.batch_alter_table("lot_reservations", schema=None) as batch_op:
        batch_op.drop_index("idx_lot_reservations_status")
        batch_op.drop_index("idx_lot_reservations_source")
        batch_op.drop_index("idx_lot_reservations_lot_status")
        batch_op.drop_index(
            "idx_lot_reservations_expires_at", postgresql_where=sa.text("expires_at IS NOT NULL")
        )

    op.drop_table("lot_reservations")
    with op.batch_alter_table("allocation_traces", schema=None) as batch_op:
        batch_op.drop_index("idx_allocation_traces_order_line")
        batch_op.drop_index("idx_allocation_traces_lot")
        batch_op.drop_index("idx_allocation_traces_created_at")

    op.drop_table("allocation_traces")
    with op.batch_alter_table("allocation_suggestions", schema=None) as batch_op:
        batch_op.drop_index("idx_allocation_suggestions_product")
        batch_op.drop_index("idx_allocation_suggestions_period")
        batch_op.drop_index("idx_allocation_suggestions_lot")
        batch_op.drop_index("idx_allocation_suggestions_forecast")
        batch_op.drop_index("idx_allocation_suggestions_customer")

    op.drop_table("allocation_suggestions")
    with op.batch_alter_table("adjustments", schema=None) as batch_op:
        batch_op.drop_index("idx_adjustments_lot")
        batch_op.drop_index("idx_adjustments_date")

    op.drop_table("adjustments")
    with op.batch_alter_table("lots", schema=None) as batch_op:
        batch_op.drop_index("idx_lots_warehouse")
        batch_op.drop_index(
            "idx_lots_temporary_lot_key", postgresql_where=sa.text("temporary_lot_key IS NOT NULL")
        )
        batch_op.drop_index("idx_lots_supplier")
        batch_op.drop_index("idx_lots_status")
        batch_op.drop_index("idx_lots_product_warehouse")
        batch_op.drop_index("idx_lots_origin_type")
        batch_op.drop_index("idx_lots_number")
        batch_op.drop_index(
            "idx_lots_expiry_date", postgresql_where=sa.text("expiry_date IS NOT NULL")
        )

    op.drop_table("lots")
    with op.batch_alter_table("expected_lots", schema=None) as batch_op:
        batch_op.drop_index("idx_expected_lots_number")
        batch_op.drop_index("idx_expected_lots_line")

    op.drop_table("expected_lots")
    with op.batch_alter_table("warehouse_delivery_routes", schema=None) as batch_op:
        batch_op.drop_index("idx_wdr_warehouse")
        batch_op.drop_index("idx_wdr_product")
        batch_op.drop_index("idx_wdr_delivery_place")
        batch_op.drop_index("idx_wdr_active")

    op.drop_table("warehouse_delivery_routes")
    with op.batch_alter_table("rpa_run_items", schema=None) as batch_op:
        batch_op.drop_index("idx_rri_complement_master")
        batch_op.drop_index("idx_rpa_run_items_run_row")
        batch_op.drop_index("idx_rpa_run_items_run_id")

    op.drop_table("rpa_run_items")
    with op.batch_alter_table("order_lines", schema=None) as batch_op:
        batch_op.drop_index("idx_order_lines_status")
        batch_op.drop_index(
            "idx_order_lines_sap_order_no", postgresql_where=sa.text("sap_order_no IS NOT NULL")
        )
        batch_op.drop_index("idx_order_lines_product")
        batch_op.drop_index("idx_order_lines_order_type")
        batch_op.drop_index("idx_order_lines_order_group")
        batch_op.drop_index("idx_order_lines_order")
        batch_op.drop_index(
            "idx_order_lines_forecast_reference",
            postgresql_where=sa.text("forecast_reference IS NOT NULL"),
        )
        batch_op.drop_index("idx_order_lines_delivery_place")
        batch_op.drop_index("idx_order_lines_date")
        batch_op.drop_index(
            "idx_order_lines_customer_order_no",
            postgresql_where=sa.text("customer_order_no IS NOT NULL"),
        )

    op.drop_table("order_lines")
    with op.batch_alter_table("inbound_plan_lines", schema=None) as batch_op:
        batch_op.drop_index("idx_inbound_plan_lines_product")
        batch_op.drop_index("idx_inbound_plan_lines_plan")

    op.drop_table("inbound_plan_lines")
    with op.batch_alter_table("forecast_current", schema=None) as batch_op:
        batch_op.drop_index("ux_forecast_current_unique")
        batch_op.drop_index("idx_forecast_current_unique")

    op.drop_table("forecast_current")
    op.drop_table("customer_item_jiku_mappings")
    with op.batch_alter_table("customer_item_delivery_settings", schema=None) as batch_op:
        batch_op.drop_index("idx_cids_jiku_code")
        batch_op.drop_index("idx_cids_delivery_place")
        batch_op.drop_index("idx_cids_customer_item")

    op.drop_table("customer_item_delivery_settings")
    with op.batch_alter_table("user_supplier_assignments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_user_supplier_primary_per_supplier", postgresql_where=sa.text("is_primary = TRUE")
        )
        batch_op.drop_index("idx_user_supplier_assignments_user")
        batch_op.drop_index("idx_user_supplier_assignments_supplier")
        batch_op.drop_index(
            "idx_user_supplier_assignments_primary", postgresql_where=sa.text("is_primary = TRUE")
        )

    op.drop_table("user_supplier_assignments")
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.drop_index("idx_user_roles_user")
        batch_op.drop_index("idx_user_roles_role")

    op.drop_table("user_roles")
    with op.batch_alter_table("system_client_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_system_client_logs_user_id")
        batch_op.drop_index("idx_system_client_logs_created_at")

    op.drop_table("system_client_logs")
    with op.batch_alter_table("rpa_runs", schema=None) as batch_op:
        batch_op.drop_index("idx_rpa_runs_type")
        batch_op.drop_index("idx_rpa_runs_status")
        batch_op.drop_index("idx_rpa_runs_customer_id")
        batch_op.drop_index("idx_rpa_runs_created_at")

    op.drop_table("rpa_runs")
    with op.batch_alter_table("product_uom_conversions", schema=None) as batch_op:
        batch_op.drop_index("idx_product_uom_conversions_valid_to")

    op.drop_table("product_uom_conversions")
    with op.batch_alter_table("product_suppliers", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_product_primary_supplier", postgresql_where=sa.text("is_primary = true")
        )
        batch_op.drop_index("idx_product_suppliers_valid_to")

    op.drop_table("product_suppliers")
    with op.batch_alter_table("product_mappings", schema=None) as batch_op:
        batch_op.drop_index("idx_product_mappings_valid_to")
        batch_op.drop_index("idx_product_mappings_supplier")
        batch_op.drop_index("idx_product_mappings_product")
        batch_op.drop_index("idx_product_mappings_customer")

    op.drop_table("product_mappings")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("idx_orders_locked_by")
        batch_op.drop_index(
            "idx_orders_lock_expires", postgresql_where=sa.text("lock_expires_at IS NOT NULL")
        )
        batch_op.drop_index("idx_orders_date")
        batch_op.drop_index("idx_orders_customer")

    op.drop_table("orders")
    with op.batch_alter_table("order_groups", schema=None) as batch_op:
        batch_op.drop_index("idx_order_groups_product")
        batch_op.drop_index("idx_order_groups_date")
        batch_op.drop_index("idx_order_groups_customer")

    op.drop_table("order_groups")
    with op.batch_alter_table("operation_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_operation_logs_user")
        batch_op.drop_index("idx_operation_logs_type")
        batch_op.drop_index("idx_operation_logs_table")
        batch_op.drop_index("idx_operation_logs_created")

    op.drop_table("operation_logs")
    with op.batch_alter_table("master_change_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_master_change_logs_user")
        batch_op.drop_index("idx_master_change_logs_table")
        batch_op.drop_index("idx_master_change_logs_record")
        batch_op.drop_index("idx_master_change_logs_changed")

    op.drop_table("master_change_logs")
    with op.batch_alter_table("inbound_plans", schema=None) as batch_op:
        batch_op.drop_index("idx_inbound_plans_supplier")
        batch_op.drop_index("idx_inbound_plans_status")
        batch_op.drop_index("idx_inbound_plans_date")

    op.drop_table("inbound_plans")
    with op.batch_alter_table("delivery_places", schema=None) as batch_op:
        batch_op.drop_index("idx_delivery_places_valid_to")
        batch_op.drop_index("idx_delivery_places_customer")

    op.drop_table("delivery_places")
    with op.batch_alter_table("customer_items", schema=None) as batch_op:
        batch_op.drop_index("idx_customer_items_valid_to")
        batch_op.drop_index("idx_customer_items_supplier")
        batch_op.drop_index("idx_customer_items_product")
        batch_op.drop_index("idx_customer_items_order_category")

    op.drop_table("customer_items")
    with op.batch_alter_table("cloud_flow_jobs", schema=None) as batch_op:
        batch_op.drop_index("idx_cloud_flow_jobs_type")
        batch_op.drop_index("idx_cloud_flow_jobs_status")
        batch_op.drop_index("idx_cloud_flow_jobs_requested_at")

    op.drop_table("cloud_flow_jobs")
    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.drop_index("idx_warehouses_valid_to")
        batch_op.drop_index("idx_warehouses_type")

    op.drop_table("warehouses")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("idx_users_username")
        batch_op.drop_index("idx_users_email")
        batch_op.drop_index("idx_users_auth_provider")
        batch_op.drop_index("idx_users_active", postgresql_where=sa.text("is_active = TRUE"))

    op.drop_table("users")
    with op.batch_alter_table("system_configs", schema=None) as batch_op:
        batch_op.drop_index("idx_system_configs_key")

    op.drop_table("system_configs")
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.drop_index("idx_suppliers_valid_to")

    op.drop_table("suppliers")
    op.drop_table("smartread_configs")
    op.drop_table("seed_snapshots")
    op.drop_table("roles")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index("idx_products_valid_to")
        batch_op.drop_index("idx_products_name")

    op.drop_table("products")
    with op.batch_alter_table("lot_reservation_history", schema=None) as batch_op:
        batch_op.drop_index("idx_lot_reservation_history_reservation")
        batch_op.drop_index("idx_lot_reservation_history_lot")
        batch_op.drop_index("idx_lot_reservation_history_changed_at")

    op.drop_table("lot_reservation_history")
    with op.batch_alter_table("layer_code_mappings", schema=None) as batch_op:
        batch_op.drop_index("idx_layer_code_mappings_maker")

    op.drop_table("layer_code_mappings")
    with op.batch_alter_table("forecast_history", schema=None) as batch_op:
        batch_op.drop_index("ix_forecast_history_key")

    op.drop_table("forecast_history")
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_index("idx_customers_valid_to")

    op.drop_table("customers")
    op.drop_table("cloud_flow_configs")
    with op.batch_alter_table("business_rules", schema=None) as batch_op:
        batch_op.drop_index("idx_business_rules_type")
        batch_op.drop_index(
            "idx_business_rules_active", postgresql_where=sa.text("is_active = TRUE")
        )

    op.drop_table("business_rules")
    with op.batch_alter_table("batch_jobs", schema=None) as batch_op:
        batch_op.drop_index("idx_batch_jobs_type")
        batch_op.drop_index("idx_batch_jobs_status")
        batch_op.drop_index("idx_batch_jobs_created")

    op.drop_table("batch_jobs")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
