"""add_lot_lock_fields

Revision ID: ab73ebe78f68
Revises: 550e261da7cb
Create Date: 2025-11-23 14:24:30.283110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab73ebe78f68'
down_revision = '550e261da7cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_column('lock_reason')

    # ### end Alembic commands ###
    # ### end Alembic commands ###
