"""baseline 2026-01-27

Revision ID: baseline_2026_01_27
Revises:
Create Date: 2026-01-27 12:20:15.650016

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "baseline_2026_01_27"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    import os

    # Get the path to the SQL file relative to this migration file
    sql_path = os.path.join(os.path.dirname(__file__), "..", "baseline_2026_01_27.sql")

    if os.path.exists(sql_path):
        with open(sql_path, encoding="utf-8") as f:
            sql = f.read()

        # Execute the SQL dump using raw connection to avoid SQLAlchemy/Alembic parsing
        # (This avoids issues with colons in strings being treated as bind parameters)
        bind = op.get_bind()
        raw_connection = bind.connection  # type: ignore[attr-defined]
        with raw_connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(sql)
    else:
        # In case the file is missing (e.g. in some environments),
        # we log or raise, but for now we expect it to exist.
        raise FileNotFoundError(f"Baseline SQL file not found: {sql_path}")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
