"""p2_schema_improvements_safe_updates

Revision ID: bd41467bfaf6
Revises: 000000000000
Create Date: 2025-12-13 13:56:04.121960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd41467bfaf6'
down_revision = '000000000000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Update stock_history constraint to include usage types
    # First drop old constraint
    try:
        op.drop_constraint('chk_stock_history_type', 'stock_history', type_='check')
    except Exception:
        # In case constraint name differs or doesn't exist, ignore (or handle gracefully)
        pass
        
    # Create new constraint including 'allocation_hold', 'allocation_release', 'withdrawal'
    op.create_check_constraint(
        'chk_stock_history_type',
        'stock_history',
        "transaction_type IN ('inbound','allocation','shipment','adjustment','return','allocation_hold','allocation_release','withdrawal')"
    )

    # 2. Update forecast_current.forecast_quantity precision to Numeric(15, 3)
    # Using execute since alter_column with type changes on postgres can be tricky with alembic wrappers sometimes, but alter_column should work.
    op.alter_column('forecast_current', 'forecast_quantity',
               existing_type=sa.Numeric(),
               type_=sa.Numeric(15, 3),
               existing_nullable=False)

    # 3. Drop duplicate indexes covered by UniqueConstraints
    # These indexes are redundant because the unique constraint already creates an index
    op.drop_index('idx_customers_code', table_name='customers')
    op.drop_index('idx_suppliers_code', table_name='suppliers')
    op.drop_index('idx_warehouses_code', table_name='warehouses')
    op.drop_index('idx_products_code', table_name='products')
    op.drop_index('idx_delivery_places_code', table_name='delivery_places')
    op.drop_index('idx_roles_code', table_name='roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse 3. Re-create dropped indexes
    op.create_index('idx_roles_code', 'roles', ['role_code'], unique=False)
    op.create_index('idx_delivery_places_code', 'delivery_places', ['delivery_place_code'], unique=False)
    op.create_index('idx_products_code', 'products', ['maker_part_code'], unique=False)
    op.create_index('idx_warehouses_code', 'warehouses', ['warehouse_code'], unique=False)
    op.create_index('idx_suppliers_code', 'suppliers', ['supplier_code'], unique=False)
    op.create_index('idx_customers_code', 'customers', ['customer_code'], unique=False)

    # Reverse 2. Revert forecast_quantity precision (remove explicit precision)
    op.alter_column('forecast_current', 'forecast_quantity',
               existing_type=sa.Numeric(15, 3),
               type_=sa.Numeric(),
               existing_nullable=False)

    # Reverse 1. Revert check constraint
    op.drop_constraint('chk_stock_history_type', 'stock_history', type_='check')
    op.create_check_constraint(
        'chk_stock_history_type',
        'stock_history',
        "transaction_type IN ('inbound','allocation','shipment','adjustment','return')"
    )
    # ### end Alembic commands ###
