"""p2_schema_improvements_naming

Revision ID: c77cd9420d29
Revises: bd41467bfaf6
Create Date: 2025-12-13 16:45:44.133661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77cd9420d29'
down_revision = 'bd41467bfaf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Rename UniqueConstraint on business_rules
    # uq_business_rules_rule_code
    op.execute('ALTER TABLE IF EXISTS business_rules RENAME CONSTRAINT business_rules_rule_code_key TO uq_business_rules_rule_code')

    # 2. Rename UniqueConstraint on users
    # uq_users_azure_object_id
    op.execute('ALTER TABLE IF EXISTS users RENAME CONSTRAINT users_azure_object_id_key TO uq_users_azure_object_id')

    # 3. Rename UniqueConstraints on inbound_plans
    # uq_inbound_plans_plan_number
    op.execute('ALTER TABLE IF EXISTS inbound_plans RENAME CONSTRAINT inbound_plans_plan_number_key TO uq_inbound_plans_plan_number')
    # uq_inbound_plans_sap_po_number
    op.execute('ALTER TABLE IF EXISTS inbound_plans RENAME CONSTRAINT inbound_plans_sap_po_number_key TO uq_inbound_plans_sap_po_number')

    # 4. Rename Index on forecast_current
    # idx_forecast_current_unique (It is an index with unique=True, not a constraint)
    op.execute('ALTER INDEX IF EXISTS ux_forecast_current_unique RENAME TO idx_forecast_current_unique')

    # 5. Rename FK on customer_item_delivery_settings
    # fk_customer_item_delivery_settings_customer_item
    op.execute('ALTER TABLE IF EXISTS customer_item_delivery_settings RENAME CONSTRAINT fk_cids_customer_item TO fk_customer_item_delivery_settings_customer_item')
    # fk_customer_item_jiku_mappings_customer_item
    op.execute('ALTER TABLE IF EXISTS customer_item_jiku_mappings RENAME CONSTRAINT fk_customer_item_jiku_customer_item TO fk_customer_item_jiku_mappings_customer_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse 5
    op.execute('ALTER TABLE IF EXISTS customer_item_jiku_mappings RENAME CONSTRAINT fk_customer_item_jiku_mappings_customer_item TO fk_customer_item_jiku_customer_item')
    op.execute('ALTER TABLE IF EXISTS customer_item_delivery_settings RENAME CONSTRAINT fk_customer_item_delivery_settings_customer_item TO fk_cids_customer_item')

    # Reverse 4
    op.execute('ALTER INDEX IF EXISTS idx_forecast_current_unique RENAME TO ux_forecast_current_unique')

    # Reverse 3
    op.execute('ALTER TABLE IF EXISTS inbound_plans RENAME CONSTRAINT uq_inbound_plans_sap_po_number TO inbound_plans_sap_po_number_key')
    op.execute('ALTER TABLE IF EXISTS inbound_plans RENAME CONSTRAINT uq_inbound_plans_plan_number TO inbound_plans_plan_number_key')

    # Reverse 2
    op.execute('ALTER TABLE IF EXISTS users RENAME CONSTRAINT uq_users_azure_object_id TO users_azure_object_id_key')

    # Reverse 1
    op.execute('ALTER TABLE IF EXISTS business_rules RENAME CONSTRAINT uq_business_rules_rule_code TO business_rules_rule_code_key')
    # ### end Alembic commands ###
