"""make_jiku_code_non_nullable

Revision ID: c842f0821023
Revises: 7c2d34fc6d97
Create Date: 2025-12-11 09:09:55.435311

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "c842f0821023"
down_revision = "7c2d34fc6d97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("delivery_places", schema=None) as batch_op:
        batch_op.execute("UPDATE delivery_places SET jiku_code = '' WHERE jiku_code IS NULL")
    op.alter_column(
        "delivery_places",
        "jiku_code",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        server_default="",
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("delivery_places", schema=None) as batch_op:
        batch_op.alter_column("jiku_code", existing_type=sa.VARCHAR(length=50), nullable=True)

    # ### end Alembic commands ###
    # ### end Alembic commands ###
