"""create_user_supplier_assignments_table

Revision ID: c86376ecd658
Revises: 491487e0a946
Create Date: 2025-11-27 20:37:48.816898

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'c86376ecd658'
down_revision = '491487e0a946'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_supplier_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'supplier_id', name='uq_user_supplier_assignments_user_supplier')
    )
    with op.batch_alter_table('user_supplier_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_user_supplier_assignments_primary', ['is_primary'], unique=False, postgresql_where=sa.text('is_primary = TRUE'))
        batch_op.create_index('idx_user_supplier_assignments_supplier', ['supplier_id'], unique=False)
        batch_op.create_index('idx_user_supplier_assignments_user', ['user_id'], unique=False)
        batch_op.create_index('uq_user_supplier_primary_per_supplier', ['supplier_id'], unique=True, postgresql_where=sa.text('is_primary = TRUE'))

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_supplier_assignments', schema=None) as batch_op:
        batch_op.drop_index('uq_user_supplier_primary_per_supplier', postgresql_where=sa.text('is_primary = TRUE'))
        batch_op.drop_index('idx_user_supplier_assignments_user')
        batch_op.drop_index('idx_user_supplier_assignments_supplier')
        batch_op.drop_index('idx_user_supplier_assignments_primary', postgresql_where=sa.text('is_primary = TRUE'))

    op.drop_table('user_supplier_assignments')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
