"""add sap snapshot columns to completed edits

Revision ID: cbaa7f63bde3
Revises: 70cdb27f5363
Create Date: 2026-01-28 13:05:26.098567

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "cbaa7f63bde3"
down_revision = "70cdb27f5363"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ocr_result_edits_completed", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sap_match_type", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("sap_matched_zkdmat_b", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("sap_supplier_code", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("sap_supplier_name", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("sap_qty_unit", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("sap_maker_item", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ocr_result_edits_completed", schema=None) as batch_op:
        batch_op.drop_column("sap_maker_item")
        batch_op.drop_column("sap_qty_unit")
        batch_op.drop_column("sap_supplier_name")
        batch_op.drop_column("sap_supplier_code")
        batch_op.drop_column("sap_matched_zkdmat_b")
        batch_op.drop_column("sap_match_type")

    # ### end Alembic commands ###
    # ### end Alembic commands ###
