"""change_order_register_row_columns_to_string

Revision ID: cdd8f9f2f79a
Revises: 40516792d7f0
Create Date: 2026-01-20 14:44:14.987470

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "cdd8f9f2f79a"
down_revision = "40516792d7f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_register_rows", schema=None) as batch_op:
        batch_op.alter_column(
            "delivery_date",
            existing_type=sa.DATE(),
            type_=sa.String(length=50),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "delivery_quantity",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=50),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_register_rows", schema=None) as batch_op:
        batch_op.alter_column(
            "delivery_quantity",
            existing_type=sa.String(length=50),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "delivery_date",
            existing_type=sa.String(length=50),
            type_=sa.DATE(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###
