"""Add smartread_export_history table

Revision ID: d1922e5e679c
Revises: a165e5cc9eb4
Create Date: 2026-01-19 18:21:53.156127

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "d1922e5e679c"
down_revision = "a165e5cc9eb4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smartread_export_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("config_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False),
        sa.Column("export_id", sa.String(length=255), nullable=False),
        sa.Column("task_date", sa.Date(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=True),
        sa.Column("wide_row_count", sa.Integer(), nullable=False),
        sa.Column("long_row_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["config_id"], ["smartread_configs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("smartread_export_history")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
