"""Update RpaRun Step3 Step4 fields

Revision ID: d2aec7a236f4
Revises: 6acff7fc6740
Create Date: 2025-12-20 11:26:45.290565

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "d2aec7a236f4"
down_revision = "6acff7fc6740"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rpa_run_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("processing_started_at", sa.DateTime(), nullable=True))

    with op.batch_alter_table("rpa_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_done_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("external_done_by_user_id", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("step4_executed_at", sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            None, "users", ["external_done_by_user_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rpa_runs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("step4_executed_at")
        batch_op.drop_column("external_done_by_user_id")
        batch_op.drop_column("external_done_at")

    with op.batch_alter_table("rpa_run_items", schema=None) as batch_op:
        batch_op.drop_column("processing_started_at")

    # ### end Alembic commands ###
    # ### end Alembic commands ###
