"""add_locked_quantity_to_lots

Revision ID: d7898334ad53
Revises: d302fd98d1de
Create Date: 2025-11-29 02:38:08.925619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7898334ad53'
down_revision = 'd302fd98d1de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add locked_quantity column
    op.add_column('lots', sa.Column('locked_quantity', sa.Numeric(15, 3), nullable=False, server_default='0'))
    
    # 2. Add check constraint for locked_quantity >= 0
    op.create_check_constraint('chk_lots_locked_quantity', 'lots', sa.column('locked_quantity') >= 0)
    
    # 3. Update allocation limit constraint
    # Drop existing constraint
    op.drop_constraint('chk_lots_allocation_limit', 'lots', type_='check')
    # Add new constraint: allocated_quantity + locked_quantity <= current_quantity
    op.create_check_constraint(
        'chk_lots_allocation_limit', 
        'lots', 
        sa.column('allocated_quantity') + sa.column('locked_quantity') <= sa.column('current_quantity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Revert allocation limit constraint
    op.drop_constraint('chk_lots_allocation_limit', 'lots', type_='check')
    op.create_check_constraint(
        'chk_lots_allocation_limit', 
        'lots', 
        sa.column('allocated_quantity') <= sa.column('current_quantity')
    )
    
    # 2. Drop check constraint for locked_quantity
    op.drop_constraint('chk_lots_locked_quantity', 'lots', type_='check')
    
    # 3. Drop locked_quantity column
    op.drop_column('lots', 'locked_quantity')
    # ### end Alembic commands ###
