"""Merge multiple heads

Revision ID: e50bd306f303
Revises: b7a1c2d3e4f5, f6b7c8d9e0f1
Create Date: 2026-01-22 00:41:05.016328

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "e50bd306f303"
down_revision = ("b7a1c2d3e4f5", "f6b7c8d9e0f1")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
