"""Make withdrawal fields nullable

Revision ID: e68cf68f7f45
Revises: c5f93754abcd
Create Date: 2025-12-10 20:25:03.754472

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "e68cf68f7f45"
down_revision = "c5f93754abcd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.alter_column(
            "lot_reference",
            existing_type=sa.VARCHAR(length=100),
            comment="Lot number (business key reference, replaces lot_id FK)",
            existing_comment="Lot number (business key reference)",
            existing_nullable=True,
        )

    with op.batch_alter_table("lot_reservations", schema=None) as batch_op:
        batch_op.alter_column(
            "source_type",
            existing_type=sa.VARCHAR(length=20),
            comment="Reservation source: 'forecast' | 'order' | 'manual'",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "source_id",
            existing_type=sa.BIGINT(),
            comment="ID of the source entity (order_line_id, forecast_group_id, etc.)",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "reserved_qty",
            existing_type=sa.NUMERIC(precision=15, scale=3),
            comment="Reserved quantity (must be positive)",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            comment="Reservation status: 'temporary' | 'active' | 'confirmed' | 'released'",
            existing_nullable=False,
            existing_server_default=sa.text("'active'::character varying"),
        )
        batch_op.alter_column(
            "expires_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="Expiration time for temporary reservations",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "confirmed_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="Timestamp when reservation was confirmed",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "released_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="Timestamp when reservation was released",
            existing_nullable=True,
        )

    with op.batch_alter_table("order_lines", schema=None) as batch_op:
        batch_op.alter_column(
            "forecast_reference",
            existing_type=sa.VARCHAR(length=100),
            comment="Forecast business key reference (replaces forecast_id FK)",
            existing_comment="Forecast business key reference",
            existing_nullable=True,
        )

    with op.batch_alter_table("withdrawals", schema=None) as batch_op:
        batch_op.alter_column("customer_id", existing_type=sa.BIGINT(), nullable=True)
        batch_op.alter_column("delivery_place_id", existing_type=sa.BIGINT(), nullable=True)
        batch_op.alter_column("withdrawn_by", existing_type=sa.BIGINT(), nullable=True)

    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("withdrawals", schema=None) as batch_op:
        batch_op.alter_column("withdrawn_by", existing_type=sa.BIGINT(), nullable=False)
        batch_op.alter_column("delivery_place_id", existing_type=sa.BIGINT(), nullable=False)
        batch_op.alter_column("customer_id", existing_type=sa.BIGINT(), nullable=False)

    with op.batch_alter_table("order_lines", schema=None) as batch_op:
        batch_op.alter_column(
            "forecast_reference",
            existing_type=sa.VARCHAR(length=100),
            comment="Forecast business key reference",
            existing_comment="Forecast business key reference (replaces forecast_id FK)",
            existing_nullable=True,
        )

    with op.batch_alter_table("lot_reservations", schema=None) as batch_op:
        batch_op.alter_column(
            "released_at",
            existing_type=postgresql.TIMESTAMP(),
            comment=None,
            existing_comment="Timestamp when reservation was released",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "confirmed_at",
            existing_type=postgresql.TIMESTAMP(),
            comment=None,
            existing_comment="Timestamp when reservation was confirmed",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "expires_at",
            existing_type=postgresql.TIMESTAMP(),
            comment=None,
            existing_comment="Expiration time for temporary reservations",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            comment=None,
            existing_comment="Reservation status: 'temporary' | 'active' | 'confirmed' | 'released'",
            existing_nullable=False,
            existing_server_default=sa.text("'active'::character varying"),
        )
        batch_op.alter_column(
            "reserved_qty",
            existing_type=sa.NUMERIC(precision=15, scale=3),
            comment=None,
            existing_comment="Reserved quantity (must be positive)",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "source_id",
            existing_type=sa.BIGINT(),
            comment=None,
            existing_comment="ID of the source entity (order_line_id, forecast_group_id, etc.)",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "source_type",
            existing_type=sa.VARCHAR(length=20),
            comment=None,
            existing_comment="Reservation source: 'forecast' | 'order' | 'manual'",
            existing_nullable=False,
        )

    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.alter_column(
            "lot_reference",
            existing_type=sa.VARCHAR(length=100),
            comment="Lot number (business key reference)",
            existing_comment="Lot number (business key reference, replaces lot_id FK)",
            existing_nullable=True,
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###
