"""merge multiple heads

Revision ID: eaa941fd2224
Revises: 5dd0b2432e9a, c8d9e0f1a2b3, d2e3f4g5h6i7
Create Date: 2026-01-23 08:53:42.740496

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "eaa941fd2224"
down_revision = ("5dd0b2432e9a", "c8d9e0f1a2b3", "d2e3f4g5h6i7")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
