"""remove_smartread_request_type

Revision ID: fe8a7a830d22
Revises: f1e2d3c4b5a6
Create Date: 2026-01-15 20:15:37.378078

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "fe8a7a830d22"
down_revision = "f1e2d3c4b5a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("smartread_configs", "request_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "smartread_configs",
        sa.Column(
            "request_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            server_default=sa.text("'sync'"),
        ),
    )
    # ### end Alembic commands ###
