"""add_inbound_no_2_and_update_v_ocr_results

Revision ID: ff46774c6969
Revises: ccc835b9204e
Create Date: 2026-01-27 10:27:48.327376

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "ff46774c6969"
down_revision = "ccc835b9204e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ocr_result_edits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("inbound_no_2", sa.String(length=100), nullable=True))
        batch_op.alter_column(
            "process_status",
            existing_type=sa.VARCHAR(length=20),
            comment=None,
            existing_comment="処理ステータス: pending(処理前), downloaded(ダウンロード済み), sap_linked(SAP連携後), completed(完了)",
            existing_nullable=False,
            existing_server_default=sa.text("'pending'::character varying"),
        )
        batch_op.alter_column(
            "error_flags",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            comment=None,
            existing_comment="バリデーションエラーフラグ（JSON形式）",
            existing_nullable=False,
            existing_server_default=sa.text("'{}'::jsonb"),
        )

    # ### end Alembic commands ###
    # ### end Alembic commands ###

    # Recreate all views from create_views.sql (includes updated v_ocr_results)
    from pathlib import Path

    conn = op.get_bind()
    views_path = Path(__file__).parent.parent.parent / "sql" / "views" / "create_views.sql"

    if views_path.exists():
        print(f"[{revision}] Recreating views from {views_path}...")
        views_sql = views_path.read_text(encoding="utf-8")

        # Split by semicolon and execute each statement
        statements = []
        current_stmt = []

        for line in views_sql.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("--"):
                continue

            current_stmt.append(line)

            if stripped.endswith(";"):
                stmt = "\n".join(current_stmt).strip()
                if stmt and stmt != ";":
                    statements.append(stmt)
                current_stmt = []

        # Execute each statement
        for stmt in statements:
            stmt_clean = stmt.rstrip(";").strip()
            if not stmt_clean:
                continue
            try:
                conn.execute(sa.text(stmt_clean))
            except Exception as e:
                # Log warning but continue
                if "does not exist" not in str(e):
                    print(f"[{revision}] Warning executing view statement: {e}")
    else:
        print(f"[{revision}] Warning: Views file not found at {views_path}")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ocr_result_edits", schema=None) as batch_op:
        batch_op.alter_column(
            "error_flags",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            comment="バリデーションエラーフラグ（JSON形式）",
            existing_nullable=False,
            existing_server_default=sa.text("'{}'::jsonb"),
        )
        batch_op.alter_column(
            "process_status",
            existing_type=sa.VARCHAR(length=20),
            comment="処理ステータス: pending(処理前), downloaded(ダウンロード済み), sap_linked(SAP連携後), completed(完了)",
            existing_nullable=False,
            existing_server_default=sa.text("'pending'::character varying"),
        )
        batch_op.drop_column("inbound_no_2")

    # ### end Alembic commands ###
    # ### end Alembic commands ###
