"""merge_heads

Revision ID: ccc835b9204e
Revises: 123456789abc, l6m7n8o9p0q1
Create Date: 2026-01-27 10:25:36.617442

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "ccc835b9204e"
down_revision = ("123456789abc", "l6m7n8o9p0q1")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
